//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.8800
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.I01.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMS.I01.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Location に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LocationHoshu_Location {
            get {
                return ResourceManager.GetString("LocationHoshu_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   物件名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LocationHoshu_PropertyName {
            get {
                return ResourceManager.GetString("LocationHoshu_PropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LocationHoshu_ShippingDivision {
            get {
                return ResourceManager.GetString("LocationHoshu_ShippingDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   受入日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_AcceptanceDate {
            get {
                return ResourceManager.GetString("NyukoSettei_AcceptanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   受入担当者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_AcceptanceStaff {
            get {
                return ResourceManager.GetString("NyukoSettei_AcceptanceStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Area に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_Area {
            get {
                return ResourceManager.GetString("NyukoSettei_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ARNo. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_ARNo {
            get {
                return ResourceManager.GetString("NyukoSettei_ARNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   集荷日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_AssemblyDate {
            get {
                return ResourceManager.GetString("NyukoSettei_AssemblyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BLNo. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_BLNo {
            get {
                return ResourceManager.GetString("NyukoSettei_BLNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BoxNo. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_BoxNo {
            get {
                return ResourceManager.GetString("NyukoSettei_BoxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BOX梱包日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_BoxPackingDate {
            get {
                return ResourceManager.GetString("NyukoSettei_BoxPackingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CODE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_Code {
            get {
                return ResourceManager.GetString("NyukoSettei_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   工事識別管理No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_ConstructionIdentityManagementNo {
            get {
                return ResourceManager.GetString("NyukoSettei_ConstructionIdentityManagementNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_Date {
            get {
                return ResourceManager.GetString("NyukoSettei_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納入先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_DeliveryDestination {
            get {
                return ResourceManager.GetString("NyukoSettei_DeliveryDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   図面追番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_DrawingAdditionalNo {
            get {
                return ResourceManager.GetString("NyukoSettei_DrawingAdditionalNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   図番/形式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_DrawingNoFormat {
            get {
                return ResourceManager.GetString("NyukoSettei_DrawingNoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Floor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_Floor {
            get {
                return ResourceManager.GetString("NyukoSettei_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内部管理用キー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_InternalManagementKey {
            get {
                return ResourceManager.GetString("NyukoSettei_InternalManagementKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インボイスNo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_InvoiceNo {
            get {
                return ResourceManager.GetString("NyukoSettei_InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名(和文) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_JpName {
            get {
                return ResourceManager.GetString("NyukoSettei_JpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Location に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_Location {
            get {
                return ResourceManager.GetString("NyukoSettei_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Memo(備考) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_Memo {
            get {
                return ResourceManager.GetString("NyukoSettei_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M-No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_MNo {
            get {
                return ResourceManager.GetString("NyukoSettei_MNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   機種 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_Model {
            get {
                return ResourceManager.GetString("NyukoSettei_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_Name {
            get {
                return ResourceManager.GetString("NyukoSettei_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送り状No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_OkurijyoNo {
            get {
                return ResourceManager.GetString("NyukoSettei_OkurijyoNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パレットNo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_PalletNo {
            get {
                return ResourceManager.GetString("NyukoSettei_PalletNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パレット梱包日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_PalletPackingDate {
            get {
                return ResourceManager.GetString("NyukoSettei_PalletPackingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   製番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_ProductNo {
            get {
                return ResourceManager.GetString("NyukoSettei_ProductNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_Quantity {
            get {
                return ResourceManager.GetString("NyukoSettei_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   区割No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_SectioningNo {
            get {
                return ResourceManager.GetString("NyukoSettei_SectioningNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   便 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_Ship {
            get {
                return ResourceManager.GetString("NyukoSettei_Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_ShipDate {
            get {
                return ResourceManager.GetString("NyukoSettei_ShipDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   運送会社 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_ShippingCompany {
            get {
                return ResourceManager.GetString("NyukoSettei_ShippingCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   状態 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_State {
            get {
                return ResourceManager.GetString("NyukoSettei_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STATUS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_Status {
            get {
                return ResourceManager.GetString("NyukoSettei_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ST-No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_STNo {
            get {
                return ResourceManager.GetString("NyukoSettei_STNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫Location に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_StockLocation {
            get {
                return ResourceManager.GetString("NyukoSettei_StockLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TagCode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_TagCode {
            get {
                return ResourceManager.GetString("NyukoSettei_TagCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   木枠No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_WoodFrameNo {
            get {
                return ResourceManager.GetString("NyukoSettei_WoodFrameNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   木枠梱包日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NyukoSettei_WoodFramePackingDate {
            get {
                return ResourceManager.GetString("NyukoSettei_WoodFramePackingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   受入日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_AcceptanceDate {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_AcceptanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   受入担当者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_AcceptanceStaff {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_AcceptanceStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Area に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_Area {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ARNo. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_ARNo {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_ARNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   集荷日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_AssemblyDate {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_AssemblyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BLNo. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_BLNo {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_BLNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BoxNo. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_BoxNo {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_BoxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BOX梱包日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_BoxPackingDate {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_BoxPackingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CODE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_Code {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   工事識別管理No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_ConstructionIdentityManagementNo {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_ConstructionIdentityManagementNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納入先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_DeliveryDestination {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_DeliveryDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   図面追番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_DrawingAdditionalNo {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_DrawingAdditionalNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   図番/形式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_DrawingNoFormat {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_DrawingNoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Floor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_Floor {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内部管理用キー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_InternalManagementKey {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_InternalManagementKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インボイスNo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_InvoiceNo {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名(和文) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_JpName {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_JpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Memo(備考) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_Memo {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M-No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_MNo {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_MNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   機種 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_Model {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_Name {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送り状No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_OkurijyoNo {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_OkurijyoNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パレットNo. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_PalletNo {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_PalletNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パレット梱包日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_PalletPackingDate {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_PalletPackingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   製番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_ProductNo {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_ProductNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_Quantity {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   区割No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_SectioningNo {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_SectioningNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExcelFiles|*.xls に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_sfdExcel_Filter {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_sfdExcel_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   明細ExcelFiles保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_sfdExcel_Title {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_sfdExcel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   便 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_Ship {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_ShipDate {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_ShipDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   運送会社 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_ShippingCompany {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_ShippingCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   状態 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_State {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STATUS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_Status {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ST-No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_STNo {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_STNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫/完了日付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_StockCompletionDate {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_StockCompletionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫Location に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_StockLocation {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_StockLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TagCode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_TagCode {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_TagCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   木枠梱包日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_WoodFrameDate {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_WoodFrameDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   木枠No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_WoodFrameNo {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_WoodFrameNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_WorkDate {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_WorkDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_WorkDescription {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_WorkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   作業者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeRirekiShokai_Worker {
            get {
                return ResourceManager.GetString("OpeRirekiShokai_Worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   受入日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_AcceptanceDate {
            get {
                return ResourceManager.GetString("ShukkoSettei_AcceptanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   受入担当者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_AcceptanceStaff {
            get {
                return ResourceManager.GetString("ShukkoSettei_AcceptanceStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Area に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_Area {
            get {
                return ResourceManager.GetString("ShukkoSettei_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ARNo. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_ARNo {
            get {
                return ResourceManager.GetString("ShukkoSettei_ARNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   集荷日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_AssemblyDate {
            get {
                return ResourceManager.GetString("ShukkoSettei_AssemblyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BLNo. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_BLNo {
            get {
                return ResourceManager.GetString("ShukkoSettei_BLNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BoxNo. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_BoxNo {
            get {
                return ResourceManager.GetString("ShukkoSettei_BoxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BOX梱包日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_BoxPackingDate {
            get {
                return ResourceManager.GetString("ShukkoSettei_BoxPackingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CODE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_Code {
            get {
                return ResourceManager.GetString("ShukkoSettei_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   工事識別管理No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_ConstructionIdentityManagementNo {
            get {
                return ResourceManager.GetString("ShukkoSettei_ConstructionIdentityManagementNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_Date {
            get {
                return ResourceManager.GetString("ShukkoSettei_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納入先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_DeliveryDestination {
            get {
                return ResourceManager.GetString("ShukkoSettei_DeliveryDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   図面追番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_DrawingAdditionalNo {
            get {
                return ResourceManager.GetString("ShukkoSettei_DrawingAdditionalNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   図番/形式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_DrawingNoFormat {
            get {
                return ResourceManager.GetString("ShukkoSettei_DrawingNoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Floor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_Floor {
            get {
                return ResourceManager.GetString("ShukkoSettei_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内部管理用キー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_InternalManagementKey {
            get {
                return ResourceManager.GetString("ShukkoSettei_InternalManagementKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インボイスNo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_InvoiceNo {
            get {
                return ResourceManager.GetString("ShukkoSettei_InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名(和文) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_JpName {
            get {
                return ResourceManager.GetString("ShukkoSettei_JpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Memo(備考) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_Memo {
            get {
                return ResourceManager.GetString("ShukkoSettei_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M-No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_MNo {
            get {
                return ResourceManager.GetString("ShukkoSettei_MNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   機種 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_Model {
            get {
                return ResourceManager.GetString("ShukkoSettei_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_Name {
            get {
                return ResourceManager.GetString("ShukkoSettei_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送り状No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_OkurijyoNo {
            get {
                return ResourceManager.GetString("ShukkoSettei_OkurijyoNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パレットNo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_PalletNo {
            get {
                return ResourceManager.GetString("ShukkoSettei_PalletNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パレット梱包日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_PalletPackingDate {
            get {
                return ResourceManager.GetString("ShukkoSettei_PalletPackingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   製番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_ProductNo {
            get {
                return ResourceManager.GetString("ShukkoSettei_ProductNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_Quantity {
            get {
                return ResourceManager.GetString("ShukkoSettei_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   区割No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_SectioningNo {
            get {
                return ResourceManager.GetString("ShukkoSettei_SectioningNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   便 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_Ship {
            get {
                return ResourceManager.GetString("ShukkoSettei_Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_ShipDate {
            get {
                return ResourceManager.GetString("ShukkoSettei_ShipDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   運送会社 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_ShippingCompany {
            get {
                return ResourceManager.GetString("ShukkoSettei_ShippingCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   状態 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_State {
            get {
                return ResourceManager.GetString("ShukkoSettei_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STATUS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_Status {
            get {
                return ResourceManager.GetString("ShukkoSettei_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ST-No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_STNo {
            get {
                return ResourceManager.GetString("ShukkoSettei_STNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫Location に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_StockLocation {
            get {
                return ResourceManager.GetString("ShukkoSettei_StockLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TagCode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_TagCode {
            get {
                return ResourceManager.GetString("ShukkoSettei_TagCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   木枠梱包日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_WoodFrameDate {
            get {
                return ResourceManager.GetString("ShukkoSettei_WoodFrameDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   木枠No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkoSettei_WoodFrameNo {
            get {
                return ResourceManager.GetString("ShukkoSettei_WoodFrameNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Area に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TanaoroshiSaiShokai_Area {
            get {
                return ResourceManager.GetString("TanaoroshiSaiShokai_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ARNo. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TanaoroshiSaiShokai_ARno {
            get {
                return ResourceManager.GetString("TanaoroshiSaiShokai_ARno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BoxNo. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TanaoroshiSaiShokai_BoxNo {
            get {
                return ResourceManager.GetString("TanaoroshiSaiShokai_BoxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CODE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TanaoroshiSaiShokai_Code {
            get {
                return ResourceManager.GetString("TanaoroshiSaiShokai_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TanaoroshiSaiShokai_Date {
            get {
                return ResourceManager.GetString("TanaoroshiSaiShokai_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納入先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TanaoroshiSaiShokai_DeliveryDestination {
            get {
                return ResourceManager.GetString("TanaoroshiSaiShokai_DeliveryDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   図面追番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TanaoroshiSaiShokai_DrawingAddtionalNo {
            get {
                return ResourceManager.GetString("TanaoroshiSaiShokai_DrawingAddtionalNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   図番/形式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TanaoroshiSaiShokai_DrawingNoFormat {
            get {
                return ResourceManager.GetString("TanaoroshiSaiShokai_DrawingNoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Floor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TanaoroshiSaiShokai_Floor {
            get {
                return ResourceManager.GetString("TanaoroshiSaiShokai_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名(和文) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TanaoroshiSaiShokai_JpName {
            get {
                return ResourceManager.GetString("TanaoroshiSaiShokai_JpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Memo(備考) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TanaoroshiSaiShokai_Memo {
            get {
                return ResourceManager.GetString("TanaoroshiSaiShokai_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M-No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TanaoroshiSaiShokai_MNo {
            get {
                return ResourceManager.GetString("TanaoroshiSaiShokai_MNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   機種 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TanaoroshiSaiShokai_Model {
            get {
                return ResourceManager.GetString("TanaoroshiSaiShokai_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TanaoroshiSaiShokai_Name {
            get {
                return ResourceManager.GetString("TanaoroshiSaiShokai_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   製番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TanaoroshiSaiShokai_ProductNo {
            get {
                return ResourceManager.GetString("TanaoroshiSaiShokai_ProductNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TanaoroshiSaiShokai_Quantity {
            get {
                return ResourceManager.GetString("TanaoroshiSaiShokai_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   区割No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TanaoroshiSaiShokai_SectioningNo {
            get {
                return ResourceManager.GetString("TanaoroshiSaiShokai_SectioningNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExcelFiles|*.xls に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TanaoroshiSaiShokai_sfdExcel_Filter {
            get {
                return ResourceManager.GetString("TanaoroshiSaiShokai_sfdExcel_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   明細ExcelFiles保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TanaoroshiSaiShokai_sfdExcel_Title {
            get {
                return ResourceManager.GetString("TanaoroshiSaiShokai_sfdExcel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   便 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TanaoroshiSaiShokai_Ship {
            get {
                return ResourceManager.GetString("TanaoroshiSaiShokai_Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   状態 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TanaoroshiSaiShokai_State {
            get {
                return ResourceManager.GetString("TanaoroshiSaiShokai_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STATUS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TanaoroshiSaiShokai_Status {
            get {
                return ResourceManager.GetString("TanaoroshiSaiShokai_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ST-No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TanaoroshiSaiShokai_STNo {
            get {
                return ResourceManager.GetString("TanaoroshiSaiShokai_STNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫Location に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TanaoroshiSaiShokai_StockLocation {
            get {
                return ResourceManager.GetString("TanaoroshiSaiShokai_StockLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   棚卸Location に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TanaoroshiSaiShokai_StocktakingLocation {
            get {
                return ResourceManager.GetString("TanaoroshiSaiShokai_StocktakingLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TagCode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TanaoroshiSaiShokai_TagCode {
            get {
                return ResourceManager.GetString("TanaoroshiSaiShokai_TagCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   受入日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_AcceptanceDate {
            get {
                return ResourceManager.GetString("ZaikoHoshu_AcceptanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   受入担当者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_AcceptanceStaff {
            get {
                return ResourceManager.GetString("ZaikoHoshu_AcceptanceStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Area に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_Area {
            get {
                return ResourceManager.GetString("ZaikoHoshu_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ARNo. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_ARNo {
            get {
                return ResourceManager.GetString("ZaikoHoshu_ARNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   集荷日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_AssemblyDate {
            get {
                return ResourceManager.GetString("ZaikoHoshu_AssemblyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BLNo. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_BLNo {
            get {
                return ResourceManager.GetString("ZaikoHoshu_BLNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BoxNo. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_BoxNo {
            get {
                return ResourceManager.GetString("ZaikoHoshu_BoxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BOX梱包日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_BoxPackingDate {
            get {
                return ResourceManager.GetString("ZaikoHoshu_BoxPackingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CODE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_Code {
            get {
                return ResourceManager.GetString("ZaikoHoshu_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   工事識別管理No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_ConstructionIdentityManagementNo {
            get {
                return ResourceManager.GetString("ZaikoHoshu_ConstructionIdentityManagementNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_Date {
            get {
                return ResourceManager.GetString("ZaikoHoshu_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納入先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_DeliveryDestination {
            get {
                return ResourceManager.GetString("ZaikoHoshu_DeliveryDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   図面追番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_DrawingAdditionalNo {
            get {
                return ResourceManager.GetString("ZaikoHoshu_DrawingAdditionalNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   図番/形式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_DrawingNoFormat {
            get {
                return ResourceManager.GetString("ZaikoHoshu_DrawingNoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Floor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_Floor {
            get {
                return ResourceManager.GetString("ZaikoHoshu_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内部管理用キー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_InternalManagementKey {
            get {
                return ResourceManager.GetString("ZaikoHoshu_InternalManagementKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インボイスNo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_InvoiceNo {
            get {
                return ResourceManager.GetString("ZaikoHoshu_InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名(和文) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_JpName {
            get {
                return ResourceManager.GetString("ZaikoHoshu_JpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Memo(備考) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_Memo {
            get {
                return ResourceManager.GetString("ZaikoHoshu_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M-No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_MNo {
            get {
                return ResourceManager.GetString("ZaikoHoshu_MNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   機種 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_Model {
            get {
                return ResourceManager.GetString("ZaikoHoshu_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_Name {
            get {
                return ResourceManager.GetString("ZaikoHoshu_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送り状No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_OkurijyoNo {
            get {
                return ResourceManager.GetString("ZaikoHoshu_OkurijyoNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パレットNo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_PalletNo {
            get {
                return ResourceManager.GetString("ZaikoHoshu_PalletNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パレット梱包日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_PalletPackingDate {
            get {
                return ResourceManager.GetString("ZaikoHoshu_PalletPackingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   製番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_Product {
            get {
                return ResourceManager.GetString("ZaikoHoshu_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_Quantity {
            get {
                return ResourceManager.GetString("ZaikoHoshu_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   区割No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_SectioningNo {
            get {
                return ResourceManager.GetString("ZaikoHoshu_SectioningNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExcelFiles|*.xls に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_sfdExcel_Filter {
            get {
                return ResourceManager.GetString("ZaikoHoshu_sfdExcel_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   明細ExcelFiles保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_sfdExcel_Title {
            get {
                return ResourceManager.GetString("ZaikoHoshu_sfdExcel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   便 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_Ship {
            get {
                return ResourceManager.GetString("ZaikoHoshu_Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   運送会社 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_ShippingCompany {
            get {
                return ResourceManager.GetString("ZaikoHoshu_ShippingCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_ShippingDate {
            get {
                return ResourceManager.GetString("ZaikoHoshu_ShippingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   状態 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_State {
            get {
                return ResourceManager.GetString("ZaikoHoshu_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STATUS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_Status {
            get {
                return ResourceManager.GetString("ZaikoHoshu_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ST-No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_STNo {
            get {
                return ResourceManager.GetString("ZaikoHoshu_STNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫Location に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_StockLocation {
            get {
                return ResourceManager.GetString("ZaikoHoshu_StockLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TagCode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_TagCode {
            get {
                return ResourceManager.GetString("ZaikoHoshu_TagCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   木枠梱包日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_WoodFrameDate {
            get {
                return ResourceManager.GetString("ZaikoHoshu_WoodFrameDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   木枠No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZaikoHoshu_WoodFrameNo {
            get {
                return ResourceManager.GetString("ZaikoHoshu_WoodFrameNo", resourceCulture);
            }
        }
    }
}
