//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.9179
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.S01.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMS.S01.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   【Box】 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BinkanIdo_Box {
            get {
                return ResourceManager.GetString("BinkanIdo_Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【Pallet】 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BinkanIdo_Pallet {
            get {
                return ResourceManager.GetString("BinkanIdo_Pallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【TAG】 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BinkanIdo_Tag {
            get {
                return ResourceManager.GetString("BinkanIdo_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【木枠】 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BinkanIdo_WoodFrame {
            get {
                return ResourceManager.GetString("BinkanIdo_WoodFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IkkatsuUpload_Cancel {
            get {
                return ResourceManager.GetString("IkkatsuUpload_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CODE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IkkatsuUpload_Code {
            get {
                return ResourceManager.GetString("IkkatsuUpload_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   図番/形式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IkkatsuUpload_DrawingNoFormat {
            get {
                return ResourceManager.GetString("IkkatsuUpload_DrawingNoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IkkatsuUpload_FileName {
            get {
                return ResourceManager.GetString("IkkatsuUpload_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名(和文) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IkkatsuUpload_JpName {
            get {
                return ResourceManager.GetString("IkkatsuUpload_JpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IkkatsuUpload_Name {
            get {
                return ResourceManager.GetString("IkkatsuUpload_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   写真 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IkkatsuUpload_Picture {
            get {
                return ResourceManager.GetString("IkkatsuUpload_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像フォルダ選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IkkatsuUpload_PictureFolderDescription {
            get {
                return ResourceManager.GetString("IkkatsuUpload_PictureFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   製番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IkkatsuUpload_ProductNo {
            get {
                return ResourceManager.GetString("IkkatsuUpload_ProductNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IkkatsuUpload_Quantity {
            get {
                return ResourceManager.GetString("IkkatsuUpload_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tag No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IkkatsuUpload_TagNo {
            get {
                return ResourceManager.GetString("IkkatsuUpload_TagNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upload に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IkkatsuUpload_Upload {
            get {
                return ResourceManager.GetString("IkkatsuUpload_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AR に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NisugataHakko_AR {
            get {
                return ResourceManager.GetString("NisugataHakko_AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AR No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NisugataHakko_ARNo {
            get {
                return ResourceManager.GetString("NisugataHakko_ARNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   宛先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NisugataHakko_Atesaki {
            get {
                return ResourceManager.GetString("NisugataHakko_Atesaki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   備考 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NisugataHakko_Bikou {
            get {
                return ResourceManager.GetString("NisugataHakko_Bikou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CAN に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NisugataHakko_Cancel {
            get {
                return ResourceManager.GetString("NisugataHakko_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CT No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NisugataHakko_CTNo {
            get {
                return ResourceManager.GetString("NisugataHakko_CTNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CT Qty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NisugataHakko_CTQty {
            get {
                return ResourceManager.GetString("NisugataHakko_CTQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同梱 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NisugataHakko_Doukon {
            get {
                return ResourceManager.GetString("NisugataHakko_Doukon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ECS No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NisugataHakko_ECSNo {
            get {
                return ResourceManager.GetString("NisugataHakko_ECSNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   GRWT に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NisugataHakko_GRWT {
            get {
                return ResourceManager.GetString("NisugataHakko_GRWT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   発行状態 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NisugataHakko_Hakkou {
            get {
                return ResourceManager.GetString("NisugataHakko_Hakkou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invoice No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NisugataHakko_InvoiceNo {
            get {
                return ResourceManager.GetString("NisugataHakko_InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Item に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NisugataHakko_Item {
            get {
                return ResourceManager.GetString("NisugataHakko_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   国内 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NisugataHakko_Kokunai {
            get {
                return ResourceManager.GetString("NisugataHakko_Kokunai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   梱包No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NisugataHakko_KonpoNo {
            get {
                return ResourceManager.GetString("NisugataHakko_KonpoNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納入先CD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NisugataHakko_NounyusakiCD {
            get {
                return ResourceManager.GetString("NisugataHakko_NounyusakiCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   P/L Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NisugataHakko_PLType {
            get {
                return ResourceManager.GetString("NisugataHakko_PLType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   製番CODE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NisugataHakko_SeibanCode {
            get {
                return ResourceManager.GetString("NisugataHakko_SeibanCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   製品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NisugataHakko_Seihinmei {
            get {
                return ResourceManager.GetString("NisugataHakko_Seihinmei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExcelFiles|*.xlsx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NisugataHakko_sfdExcel_Filter {
            get {
                return ResourceManager.GetString("NisugataHakko_sfdExcel_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   荷姿表ExcelFile保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NisugataHakko_sfdExcel_Title {
            get {
                return ResourceManager.GetString("NisugataHakko_sfdExcel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ship に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NisugataHakko_Ship {
            get {
                return ResourceManager.GetString("NisugataHakko_Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size H に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NisugataHakko_SizeH {
            get {
                return ResourceManager.GetString("NisugataHakko_SizeH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size L に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NisugataHakko_SizeL {
            get {
                return ResourceManager.GetString("NisugataHakko_SizeL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size W に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NisugataHakko_SizeW {
            get {
                return ResourceManager.GetString("NisugataHakko_SizeW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   定形 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NisugataHakko_Teikei {
            get {
                return ResourceManager.GetString("NisugataHakko_Teikei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   運送会社 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NisugataHakko_UnsoKaisha {
            get {
                return ResourceManager.GetString("NisugataHakko_UnsoKaisha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷元 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NounyusakiHoshu_SipFromName {
            get {
                return ResourceManager.GetString("NounyusakiHoshu_SipFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   物件名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikaku_BukkenName {
            get {
                return ResourceManager.GetString("ShukkaKeikaku_BukkenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有償/無償 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikaku_EstimateFlag {
            get {
                return ResourceManager.GetString("ShukkaKeikaku_EstimateFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   機械Parts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikaku_KikaiParts {
            get {
                return ResourceManager.GetString("ShukkaKeikaku_KikaiParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   機種 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikaku_Model {
            get {
                return ResourceManager.GetString("ShukkaKeikaku_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内容 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikaku_Naiyo {
            get {
                return ResourceManager.GetString("ShukkaKeikaku_Naiyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数値が入力可能です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikaku_Numeric {
            get {
                return ResourceManager.GetString("ShukkaKeikaku_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   環境依存文字は使用できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikaku_PlatformDependentChar {
            get {
                return ResourceManager.GetString("ShukkaKeikaku_PlatformDependentChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷計画ExcelFiles選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikaku_RefDlgTitle {
            get {
                return ResourceManager.GetString("ShukkaKeikaku_RefDlgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   備考 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikaku_Remarks {
            get {
                return ResourceManager.GetString("ShukkaKeikaku_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExcelFiles|*.xlsx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikaku_sdfExcel_Filter {
            get {
                return ResourceManager.GetString("ShukkaKeikaku_sdfExcel_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   製番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikaku_Seiban {
            get {
                return ResourceManager.GetString("ShukkaKeikaku_Seiban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   制御Parts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikaku_SeigyoParts {
            get {
                return ResourceManager.GetString("ShukkaKeikaku_SeigyoParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷計画ExcelFiles保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikaku_sfdExcel_Title {
            get {
                return ResourceManager.GetString("ShukkaKeikaku_sfdExcel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   便 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikaku_Ship {
            get {
                return ResourceManager.GetString("ShukkaKeikaku_Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   案件管理No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikaku_ShipNo {
            get {
                return ResourceManager.GetString("ShukkaKeikaku_ShipNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   運賃・梱包 製番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikaku_ShipSeiban {
            get {
                return ResourceManager.GetString("ShukkaKeikaku_ShipSeiban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理フラグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikaku_ShoriFlag {
            get {
                return ResourceManager.GetString("ShukkaKeikaku_ShoriFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikaku_ShukkaDate {
            get {
                return ResourceManager.GetString("ShukkaKeikaku_ShukkaDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷元 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikaku_ShukkaFrom {
            get {
                return ResourceManager.GetString("ShukkaKeikaku_ShukkaFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikaku_ShukkaTo {
            get {
                return ResourceManager.GetString("ShukkaKeikaku_ShukkaTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   半角英数が入力可能です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikaku_Singlebyte {
            get {
                return ResourceManager.GetString("ShukkaKeikaku_Singlebyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   到着予定日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikaku_TouchakuyoteiDate {
            get {
                return ResourceManager.GetString("ShukkaKeikaku_TouchakuyoteiDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AIR/SHIP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikaku_TransportFlag {
            get {
                return ResourceManager.GetString("ShukkaKeikaku_TransportFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   英大文字、数値が入力可能です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikaku_UpperAndNumber {
            get {
                return ResourceManager.GetString("ShukkaKeikaku_UpperAndNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   受入日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_AcceptanceDate {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_AcceptanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   受入担当者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_AcceptanceStaff {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_AcceptanceStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Area に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_Area {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AR No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_ArNo {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_ArNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   集荷日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_AssemblyDate {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_AssemblyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BLNo. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_BLNo {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_BLNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BoxNo. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_BoxNo {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_BoxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Box梱包日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_BoxPackingDate {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_BoxPackingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CODE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_Code {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通関確認状態 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_CustomsStatus {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_CustomsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納入先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_DeliveryDestination {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_DeliveryDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   区割No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_DivisionNo {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_DivisionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   図面追番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_DrawingAdditionalNo {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_DrawingAdditionalNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   図番/形式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_DrawingNoFormat {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_DrawingNoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Floor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_Floor {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Free1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_Free1 {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_Free1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Free2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_Free2 {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_Free2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   重量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_Grwt {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_Grwt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   INVOICENo. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_InvoiceNo {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名(和文) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_JpName {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_JpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Memo(備考) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_Memo {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M-No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_MNo {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_MNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   機種 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_Model {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_Name {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数値が入力可能です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_Numeric {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   送り状No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_OkurijyoNo {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_OkurijyoNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PalletNo. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_PalletNo {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_PalletNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pallet梱包日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_PalletPackingDate {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_PalletPackingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   写真 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_Picture {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   環境依存文字は使用できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_PlatformDependentChar {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_PlatformDependentChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   製番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_ProductNo {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_ProductNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_Quantity {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   備考 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_Remarks {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExcelFiles|*.xls に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_sdfExcel_Filter {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_sdfExcel_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   明細ExcelFiles保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_sdfExcel_Ttitle {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_sdfExcel_Ttitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   区割No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_SectioningNo {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_SectioningNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   運送会社 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_ShippingCompany {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_ShippingCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_ShippingDate {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_ShippingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷便 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_ShippingFlights {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_ShippingFlights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   半角英数が入力可能です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_Singlebyte {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_Singlebyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷元 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_SipFromName {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_SipFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   状態 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_State {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ST-No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_STNo {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_STNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tag No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_TagNo {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_TagNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TAG便名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_TagShip {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_TagShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   連携No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_TehaiRenkeiNo {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_TehaiRenkeiNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   英大文字、数値が入力可能です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_UpperAndNumber {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_UpperAndNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_Version {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   木枠No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_WoodFrameNo {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_WoodFrameNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   木枠梱包日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_WoodFramePackingDate {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_WoodFramePackingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   図番/形式2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuMeisai_ZUMEN_KEISHIKI2 {
            get {
                return ResourceManager.GetString("ShukkaKeikakuMeisai_ZUMEN_KEISHIKI2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AR No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkakeikakuRenkei_ARNo {
            get {
                return ResourceManager.GetString("ShukkakeikakuRenkei_ARNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ECS No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkakeikakuRenkei_ECSNo {
            get {
                return ResourceManager.GetString("ShukkakeikakuRenkei_ECSNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkakeikakuRenkei_Hinmei {
            get {
                return ResourceManager.GetString("ShukkakeikakuRenkei_Hinmei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名(和文) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkakeikakuRenkei_Hinmei_jp {
            get {
                return ResourceManager.GetString("ShukkakeikakuRenkei_Hinmei_jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷明細数量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkakeikakuRenkei_SMeisaiNum {
            get {
                return ResourceManager.GetString("ShukkakeikakuRenkei_SMeisaiNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkakeikakuRenkei_Syukkasu {
            get {
                return ResourceManager.GetString("ShukkakeikakuRenkei_Syukkasu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TAG登録許容数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkakeikakuRenkei_TagAllow {
            get {
                return ResourceManager.GetString("ShukkakeikakuRenkei_TagAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TAG登録可能数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkakeikakuRenkei_TagMax {
            get {
                return ResourceManager.GetString("ShukkakeikakuRenkei_TagMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TAG登録数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkakeikakuRenkei_TagNum {
            get {
                return ResourceManager.GetString("ShukkakeikakuRenkei_TagNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   手配No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkakeikakuRenkei_TehaiNo {
            get {
                return ResourceManager.GetString("ShukkakeikakuRenkei_TehaiNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   手配連携No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkakeikakuRenkei_TehaiRenkeiNo {
            get {
                return ResourceManager.GetString("ShukkakeikakuRenkei_TehaiRenkeiNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkakeikakuRenkei_Version {
            get {
                return ResourceManager.GetString("ShukkakeikakuRenkei_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   残数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkakeikakuRenkei_Zansu {
            get {
                return ResourceManager.GetString("ShukkakeikakuRenkei_Zansu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   図番/型式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkakeikakuRenkei_Zuban {
            get {
                return ResourceManager.GetString("ShukkakeikakuRenkei_Zuban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   備考 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuShokai_Biko {
            get {
                return ResourceManager.GetString("ShukkaKeikakuShokai_Biko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   物件名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuShokai_BukkenName {
            get {
                return ResourceManager.GetString("ShukkaKeikakuShokai_BukkenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   荷受先CD に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuShokai_ConsignCD {
            get {
                return ResourceManager.GetString("ShukkaKeikakuShokai_ConsignCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有償/無償 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuShokai_EstimateFlag {
            get {
                return ResourceManager.GetString("ShukkaKeikakuShokai_EstimateFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   有償 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuShokai_EstimateFlag_Commercial {
            get {
                return ResourceManager.GetString("ShukkaKeikakuShokai_EstimateFlag_Commercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無償 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuShokai_EstimateFlag_Noncommercial {
            get {
                return ResourceManager.GetString("ShukkaKeikakuShokai_EstimateFlag_Noncommercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   物量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuShokai_GenbayoButsuryo {
            get {
                return ResourceManager.GetString("ShukkaKeikakuShokai_GenbayoButsuryo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   状態 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuShokai_GenbayoStatus {
            get {
                return ResourceManager.GetString("ShukkaKeikakuShokai_GenbayoStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   機械Parts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuShokai_KikaiParts {
            get {
                return ResourceManager.GetString("ShukkaKeikakuShokai_KikaiParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   機種 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuShokai_KiShu {
            get {
                return ResourceManager.GetString("ShukkaKeikakuShokai_KiShu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   状態 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuShokai_Min_JyotaiFlag {
            get {
                return ResourceManager.GetString("ShukkaKeikakuShokai_Min_JyotaiFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内容 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuShokai_Naiyo {
            get {
                return ResourceManager.GetString("ShukkaKeikakuShokai_Naiyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   製番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuShokai_Seiban {
            get {
                return ResourceManager.GetString("ShukkaKeikakuShokai_Seiban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   制御Parts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuShokai_SeigyoParts {
            get {
                return ResourceManager.GetString("ShukkaKeikakuShokai_SeigyoParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全て に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuShokai_SelectAll {
            get {
                return ResourceManager.GetString("ShukkaKeikakuShokai_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExcelFiles|*.xlsx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuShokai_sfdExcel_Filter {
            get {
                return ResourceManager.GetString("ShukkaKeikakuShokai_sfdExcel_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   明細ExcelFiles保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuShokai_sfdExcel_Title {
            get {
                return ResourceManager.GetString("ShukkaKeikakuShokai_sfdExcel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   便名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuShokai_Ship {
            get {
                return ResourceManager.GetString("ShukkaKeikakuShokai_Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   運賃・梱包製番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuShokai_ShipSeiban {
            get {
                return ResourceManager.GetString("ShukkaKeikakuShokai_ShipSeiban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処理フラグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuShokai_ShoriFlag {
            get {
                return ResourceManager.GetString("ShukkaKeikakuShokai_ShoriFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuShokai_ShukkaDate {
            get {
                return ResourceManager.GetString("ShukkaKeikakuShokai_ShukkaDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷元 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuShokai_ShukkaFrom {
            get {
                return ResourceManager.GetString("ShukkaKeikakuShokai_ShukkaFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuShokai_ShukkaTo {
            get {
                return ResourceManager.GetString("ShukkaKeikakuShokai_ShukkaTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TAG発行状況 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuShokai_TagNum {
            get {
                return ResourceManager.GetString("ShukkaKeikakuShokai_TagNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ステータス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuShokai_TagStatus {
            get {
                return ResourceManager.GetString("ShukkaKeikakuShokai_TagStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   到着予定日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuShokai_TouchakuyoteiDate {
            get {
                return ResourceManager.GetString("ShukkaKeikakuShokai_TouchakuyoteiDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AIR/SHIP に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkaKeikakuShokai_TransportFlag {
            get {
                return ResourceManager.GetString("ShukkaKeikakuShokai_TransportFlag", resourceCulture);
            }
        }
    }
}
