//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.9179
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemBase.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemBase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap App {
            get {
                object obj = ResourceManager.GetObject("App", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   内容が変更されています。\r\n変更を確定せず画面を閉じてもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BaseForm_ChangedCloseQuestion {
            get {
                return ResourceManager.GetString("BaseForm_ChangedCloseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画面を閉じてもよろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BaseForm_CloseQuestion {
            get {
                return ResourceManager.GetString("BaseForm_CloseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BaseLogin_Login {
            get {
                return ResourceManager.GetString("BaseLogin_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Menu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BaseSDIMenu_Menu {
            get {
                return ResourceManager.GetString("BaseSDIMenu_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BaseSDIMenu_Version {
            get {
                return ResourceManager.GetString("BaseSDIMenu_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバー接続確認中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BaseSplash_BeginConnect {
            get {
                return ResourceManager.GetString("BaseSplash_BeginConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初期化処理中 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BaseSplash_BeginInit {
            get {
                return ResourceManager.GetString("BaseSplash_BeginInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初期化処理失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BaseSplash_BeginInitFailed {
            get {
                return ResourceManager.GetString("BaseSplash_BeginInitFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システム起動準備完了、システムを開始します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BaseSplash_Complete {
            get {
                return ResourceManager.GetString("BaseSplash_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバー接続失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BaseSplash_ConnectFailed {
            get {
                return ResourceManager.GetString("BaseSplash_ConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サーバー接続完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BaseSplash_ConnectSuccess {
            get {
                return ResourceManager.GetString("BaseSplash_ConnectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BaseSplash_Version {
            get {
                return ResourceManager.GetString("BaseSplash_Version", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Chord {
            get {
                return ResourceManager.GetStream("Chord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CustomMsgBoxEx_Confirmation {
            get {
                return ResourceManager.GetString("CustomMsgBoxEx_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CustomMsgBoxEx_Error {
            get {
                return ResourceManager.GetString("CustomMsgBoxEx_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CustomMsgBoxEx_Information {
            get {
                return ResourceManager.GetString("CustomMsgBoxEx_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   警告 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CustomMsgBoxEx_Warning {
            get {
                return ResourceManager.GetString("CustomMsgBoxEx_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダを選択してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CustomOrderForm_ShowSaveFolderDialogFileName {
            get {
                return ResourceManager.GetString("CustomOrderForm_ShowSaveFolderDialogFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダ|. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CustomOrderForm_ShowSaveFolderDialogFilter {
            get {
                return ResourceManager.GetString("CustomOrderForm_ShowSaveFolderDialogFilter", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Ding {
            get {
                return ResourceManager.GetStream("Ding", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon Error {
            get {
                object obj = ResourceManager.GetObject("Error", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Infomation {
            get {
                object obj = ResourceManager.GetObject("Infomation", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   中止(&amp;A) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_Abort {
            get {
                return ResourceManager.GetString("MessageBoxEx_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_Cancel {
            get {
                return ResourceManager.GetString("MessageBoxEx_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExceptionMessage:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_ExceptionMessage {
            get {
                return ResourceManager.GetString("MessageBoxEx_ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exception:NULL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_ExceptionNone {
            get {
                return ResourceManager.GetString("MessageBoxEx_ExceptionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExceptionSource:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_ExceptionSource {
            get {
                return ResourceManager.GetString("MessageBoxEx_ExceptionSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExceptionStackTrace:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_ExceptionStackTrace {
            get {
                return ResourceManager.GetString("MessageBoxEx_ExceptionStackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無視(&amp;I) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_Ignore {
            get {
                return ResourceManager.GetString("MessageBoxEx_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CLR実行バージョン:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_InfoErrorAppImageRuntimeEnvironmentVersion {
            get {
                return ResourceManager.GetString("MessageBoxEx_InfoErrorAppImageRuntimeEnvironmentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CLRビルドバージョン:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_InfoErrorAppImageRuntimeVersion {
            get {
                return ResourceManager.GetString("MessageBoxEx_InfoErrorAppImageRuntimeVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [アプリケーション情報] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_InfoErrorAppInfoTitle {
            get {
                return ResourceManager.GetString("MessageBoxEx_InfoErrorAppInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   製品名:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_InfoErrorAppProductName {
            get {
                return ResourceManager.GetString("MessageBoxEx_InfoErrorAppProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_InfoErrorAppProductVersion {
            get {
                return ResourceManager.GetString("MessageBoxEx_InfoErrorAppProductVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Detail:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_InfoErrorExceptionDetail {
            get {
                return ResourceManager.GetString("MessageBoxEx_InfoErrorExceptionDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Message:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_InfoErrorExceptionMessage {
            get {
                return ResourceManager.GetString("MessageBoxEx_InfoErrorExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [例外情報] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_InfoErrorExceptionTitle {
            get {
                return ResourceManager.GetString("MessageBoxEx_InfoErrorExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OS情報:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_InfoErrorOSInfo {
            get {
                return ResourceManager.GetString("MessageBoxEx_InfoErrorOSInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [OS情報] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_InfoErrorOSInfoTitle {
            get {
                return ResourceManager.GetString("MessageBoxEx_InfoErrorOSInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コンピューター名:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_InfoErrorUserInfoComputerName {
            get {
                return ResourceManager.GetString("MessageBoxEx_InfoErrorUserInfoComputerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ドメイン名:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_InfoErrorUserInfoDomainName {
            get {
                return ResourceManager.GetString("MessageBoxEx_InfoErrorUserInfoDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホスト名:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_InfoErrorUserInfoHostName {
            get {
                return ResourceManager.GetString("MessageBoxEx_InfoErrorUserInfoHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IPアドレス{0}:{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_InfoErrorUserInfoIpAddress {
            get {
                return ResourceManager.GetString("MessageBoxEx_InfoErrorUserInfoIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Administrator権限:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_InfoErrorUserInfoIsAdministrator {
            get {
                return ResourceManager.GetString("MessageBoxEx_InfoErrorUserInfoIsAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PowerUser権限:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_InfoErrorUserInfoIsPowerUser {
            get {
                return ResourceManager.GetString("MessageBoxEx_InfoErrorUserInfoIsPowerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User権限:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_InfoErrorUserInfoIsUser {
            get {
                return ResourceManager.GetString("MessageBoxEx_InfoErrorUserInfoIsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ユーザー情報] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_InfoErrorUserInfoTitle {
            get {
                return ResourceManager.GetString("MessageBoxEx_InfoErrorUserInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー名(フル):{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_InfoErrorUserInfoUserFullName {
            get {
                return ResourceManager.GetString("MessageBoxEx_InfoErrorUserInfoUserFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザー名:{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_InfoErrorUserInfoUserName {
            get {
                return ResourceManager.GetString("MessageBoxEx_InfoErrorUserInfoUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   いいえ(&amp;N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_No {
            get {
                return ResourceManager.GetString("MessageBoxEx_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_Ok {
            get {
                return ResourceManager.GetString("MessageBoxEx_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再試行(&amp;R) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_Retry {
            get {
                return ResourceManager.GetString("MessageBoxEx_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filesの作成に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_SaveErrorMsgDescription {
            get {
                return ResourceManager.GetString("MessageBoxEx_SaveErrorMsgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_SaveErrorMsgTitle {
            get {
                return ResourceManager.GetString("MessageBoxEx_SaveErrorMsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error{0:yyyyMMddHHmmss}.txt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_SaveFileName {
            get {
                return ResourceManager.GetString("MessageBoxEx_SaveFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   はい(&amp;Y) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MessageBoxEx_Yes {
            get {
                return ResourceManager.GetString("MessageBoxEx_Yes", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon Question {
            get {
                object obj = ResourceManager.GetObject("Question", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VersionJoho_Title {
            get {
                return ResourceManager.GetString("VersionJoho_Title", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon Warning {
            get {
                object obj = ResourceManager.GetObject("Warning", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
