//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.9174
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// このソース コードは Microsoft.VSDesigner、バージョン 2.0.50727.9174 によって自動生成されました。
// 
#pragma warning disable 1591

namespace WsConnection.WebRefK02 {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsK02Soap", Namespace="http://smssrv/")]
    public partial class WsK02 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetNoListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBoxListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMeisaiOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNonyusakiOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdBoxNoKanriOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPalletListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPalletNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBoxDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdPalletNoKanriOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPackingListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPackingMeisaiOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetKiwakuKonpoTorokuDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckKiwakuKonpoTorokuEditOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdKiwakuKonpoTorokuOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetKiwakuKonpoMeisaiDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMoveShipDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetKiwakuKonpoShukkaMeisaiFirstRowDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdKiwakuKonpoMeisaiTorokuOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetKiwakuMatomeDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMatomePackingMeisaiOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendCondBaseOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsK02() {
            this.Url = global::WsConnection.Properties.Settings.Default.WsConnection_WebRefK02_WsK02;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetNoListCompletedEventHandler GetNoListCompleted;
        
        /// <remarks/>
        public event GetBoxListCompletedEventHandler GetBoxListCompleted;
        
        /// <remarks/>
        public event GetMeisaiCompletedEventHandler GetMeisaiCompleted;
        
        /// <remarks/>
        public event GetNonyusakiCompletedEventHandler GetNonyusakiCompleted;
        
        /// <remarks/>
        public event UpdBoxNoKanriCompletedEventHandler UpdBoxNoKanriCompleted;
        
        /// <remarks/>
        public event GetPalletListCompletedEventHandler GetPalletListCompleted;
        
        /// <remarks/>
        public event GetPalletNoCompletedEventHandler GetPalletNoCompleted;
        
        /// <remarks/>
        public event GetBoxDataCompletedEventHandler GetBoxDataCompleted;
        
        /// <remarks/>
        public event UpdPalletNoKanriCompletedEventHandler UpdPalletNoKanriCompleted;
        
        /// <remarks/>
        public event GetPackingListCompletedEventHandler GetPackingListCompleted;
        
        /// <remarks/>
        public event GetPackingMeisaiCompletedEventHandler GetPackingMeisaiCompleted;
        
        /// <remarks/>
        public event GetKiwakuKonpoTorokuDataCompletedEventHandler GetKiwakuKonpoTorokuDataCompleted;
        
        /// <remarks/>
        public event CheckKiwakuKonpoTorokuEditCompletedEventHandler CheckKiwakuKonpoTorokuEditCompleted;
        
        /// <remarks/>
        public event UpdKiwakuKonpoTorokuCompletedEventHandler UpdKiwakuKonpoTorokuCompleted;
        
        /// <remarks/>
        public event GetKiwakuKonpoMeisaiDataCompletedEventHandler GetKiwakuKonpoMeisaiDataCompleted;
        
        /// <remarks/>
        public event GetMoveShipDataCompletedEventHandler GetMoveShipDataCompleted;
        
        /// <remarks/>
        public event GetKiwakuKonpoShukkaMeisaiFirstRowDataCompletedEventHandler GetKiwakuKonpoShukkaMeisaiFirstRowDataCompleted;
        
        /// <remarks/>
        public event UpdKiwakuKonpoMeisaiTorokuCompletedEventHandler UpdKiwakuKonpoMeisaiTorokuCompleted;
        
        /// <remarks/>
        public event GetKiwakuMatomeDataCompletedEventHandler GetKiwakuMatomeDataCompleted;
        
        /// <remarks/>
        public event GetMatomePackingMeisaiCompletedEventHandler GetMatomePackingMeisaiCompleted;
        
        /// <remarks/>
        public event SendCondBaseCompletedEventHandler SendCondBaseCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetNoList", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetNoList(CondK02 cond, out System.Data.DataTable noList, out string errorMsgID) {
            object[] results = this.Invoke("GetNoList", new object[] {
                        cond});
            noList = ((System.Data.DataTable)(results[1]));
            errorMsgID = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetNoListAsync(CondK02 cond) {
            this.GetNoListAsync(cond, null);
        }
        
        /// <remarks/>
        public void GetNoListAsync(CondK02 cond, object userState) {
            if ((this.GetNoListOperationCompleted == null)) {
                this.GetNoListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNoListOperationCompleted);
            }
            this.InvokeAsync("GetNoList", new object[] {
                        cond}, this.GetNoListOperationCompleted, userState);
        }
        
        private void OnGetNoListOperationCompleted(object arg) {
            if ((this.GetNoListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNoListCompleted(this, new GetNoListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetBoxList", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetBoxList() {
            object[] results = this.Invoke("GetBoxList", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetBoxListAsync() {
            this.GetBoxListAsync(null);
        }
        
        /// <remarks/>
        public void GetBoxListAsync(object userState) {
            if ((this.GetBoxListOperationCompleted == null)) {
                this.GetBoxListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBoxListOperationCompleted);
            }
            this.InvokeAsync("GetBoxList", new object[0], this.GetBoxListOperationCompleted, userState);
        }
        
        private void OnGetBoxListOperationCompleted(object arg) {
            if ((this.GetBoxListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBoxListCompleted(this, new GetBoxListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetMeisai", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetMeisai(System.Data.DataTable dt) {
            object[] results = this.Invoke("GetMeisai", new object[] {
                        dt});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetMeisaiAsync(System.Data.DataTable dt) {
            this.GetMeisaiAsync(dt, null);
        }
        
        /// <remarks/>
        public void GetMeisaiAsync(System.Data.DataTable dt, object userState) {
            if ((this.GetMeisaiOperationCompleted == null)) {
                this.GetMeisaiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMeisaiOperationCompleted);
            }
            this.InvokeAsync("GetMeisai", new object[] {
                        dt}, this.GetMeisaiOperationCompleted, userState);
        }
        
        private void OnGetMeisaiOperationCompleted(object arg) {
            if ((this.GetMeisaiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMeisaiCompleted(this, new GetMeisaiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetNonyusaki", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetNonyusaki(CondK02 cond) {
            object[] results = this.Invoke("GetNonyusaki", new object[] {
                        cond});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetNonyusakiAsync(CondK02 cond) {
            this.GetNonyusakiAsync(cond, null);
        }
        
        /// <remarks/>
        public void GetNonyusakiAsync(CondK02 cond, object userState) {
            if ((this.GetNonyusakiOperationCompleted == null)) {
                this.GetNonyusakiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNonyusakiOperationCompleted);
            }
            this.InvokeAsync("GetNonyusaki", new object[] {
                        cond}, this.GetNonyusakiOperationCompleted, userState);
        }
        
        private void OnGetNonyusakiOperationCompleted(object arg) {
            if ((this.GetNonyusakiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNonyusakiCompleted(this, new GetNonyusakiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/UpdBoxNoKanri", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdBoxNoKanri(CondK02 cond, System.Data.DataTable dt) {
            this.Invoke("UpdBoxNoKanri", new object[] {
                        cond,
                        dt});
        }
        
        /// <remarks/>
        public void UpdBoxNoKanriAsync(CondK02 cond, System.Data.DataTable dt) {
            this.UpdBoxNoKanriAsync(cond, dt, null);
        }
        
        /// <remarks/>
        public void UpdBoxNoKanriAsync(CondK02 cond, System.Data.DataTable dt, object userState) {
            if ((this.UpdBoxNoKanriOperationCompleted == null)) {
                this.UpdBoxNoKanriOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdBoxNoKanriOperationCompleted);
            }
            this.InvokeAsync("UpdBoxNoKanri", new object[] {
                        cond,
                        dt}, this.UpdBoxNoKanriOperationCompleted, userState);
        }
        
        private void OnUpdBoxNoKanriOperationCompleted(object arg) {
            if ((this.UpdBoxNoKanriCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdBoxNoKanriCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetPalletList", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetPalletList() {
            object[] results = this.Invoke("GetPalletList", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetPalletListAsync() {
            this.GetPalletListAsync(null);
        }
        
        /// <remarks/>
        public void GetPalletListAsync(object userState) {
            if ((this.GetPalletListOperationCompleted == null)) {
                this.GetPalletListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPalletListOperationCompleted);
            }
            this.InvokeAsync("GetPalletList", new object[0], this.GetPalletListOperationCompleted, userState);
        }
        
        private void OnGetPalletListOperationCompleted(object arg) {
            if ((this.GetPalletListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPalletListCompleted(this, new GetPalletListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetPalletNo", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetPalletNo(CondK02 cond) {
            object[] results = this.Invoke("GetPalletNo", new object[] {
                        cond});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetPalletNoAsync(CondK02 cond) {
            this.GetPalletNoAsync(cond, null);
        }
        
        /// <remarks/>
        public void GetPalletNoAsync(CondK02 cond, object userState) {
            if ((this.GetPalletNoOperationCompleted == null)) {
                this.GetPalletNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPalletNoOperationCompleted);
            }
            this.InvokeAsync("GetPalletNo", new object[] {
                        cond}, this.GetPalletNoOperationCompleted, userState);
        }
        
        private void OnGetPalletNoOperationCompleted(object arg) {
            if ((this.GetPalletNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPalletNoCompleted(this, new GetPalletNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetBoxData", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetBoxData(System.Data.DataTable dt) {
            object[] results = this.Invoke("GetBoxData", new object[] {
                        dt});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetBoxDataAsync(System.Data.DataTable dt) {
            this.GetBoxDataAsync(dt, null);
        }
        
        /// <remarks/>
        public void GetBoxDataAsync(System.Data.DataTable dt, object userState) {
            if ((this.GetBoxDataOperationCompleted == null)) {
                this.GetBoxDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBoxDataOperationCompleted);
            }
            this.InvokeAsync("GetBoxData", new object[] {
                        dt}, this.GetBoxDataOperationCompleted, userState);
        }
        
        private void OnGetBoxDataOperationCompleted(object arg) {
            if ((this.GetBoxDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBoxDataCompleted(this, new GetBoxDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/UpdPalletNoKanri", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdPalletNoKanri(CondK02 cond, System.Data.DataTable dt) {
            this.Invoke("UpdPalletNoKanri", new object[] {
                        cond,
                        dt});
        }
        
        /// <remarks/>
        public void UpdPalletNoKanriAsync(CondK02 cond, System.Data.DataTable dt) {
            this.UpdPalletNoKanriAsync(cond, dt, null);
        }
        
        /// <remarks/>
        public void UpdPalletNoKanriAsync(CondK02 cond, System.Data.DataTable dt, object userState) {
            if ((this.UpdPalletNoKanriOperationCompleted == null)) {
                this.UpdPalletNoKanriOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdPalletNoKanriOperationCompleted);
            }
            this.InvokeAsync("UpdPalletNoKanri", new object[] {
                        cond,
                        dt}, this.UpdPalletNoKanriOperationCompleted, userState);
        }
        
        private void OnUpdPalletNoKanriOperationCompleted(object arg) {
            if ((this.UpdPalletNoKanriCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdPalletNoKanriCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetPackingList", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetPackingList(CondK02 cond) {
            object[] results = this.Invoke("GetPackingList", new object[] {
                        cond});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetPackingListAsync(CondK02 cond) {
            this.GetPackingListAsync(cond, null);
        }
        
        /// <remarks/>
        public void GetPackingListAsync(CondK02 cond, object userState) {
            if ((this.GetPackingListOperationCompleted == null)) {
                this.GetPackingListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPackingListOperationCompleted);
            }
            this.InvokeAsync("GetPackingList", new object[] {
                        cond}, this.GetPackingListOperationCompleted, userState);
        }
        
        private void OnGetPackingListOperationCompleted(object arg) {
            if ((this.GetPackingListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPackingListCompleted(this, new GetPackingListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetPackingMeisai", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetPackingMeisai(CondK02 cond, System.Data.DataTable dt) {
            object[] results = this.Invoke("GetPackingMeisai", new object[] {
                        cond,
                        dt});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetPackingMeisaiAsync(CondK02 cond, System.Data.DataTable dt) {
            this.GetPackingMeisaiAsync(cond, dt, null);
        }
        
        /// <remarks/>
        public void GetPackingMeisaiAsync(CondK02 cond, System.Data.DataTable dt, object userState) {
            if ((this.GetPackingMeisaiOperationCompleted == null)) {
                this.GetPackingMeisaiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPackingMeisaiOperationCompleted);
            }
            this.InvokeAsync("GetPackingMeisai", new object[] {
                        cond,
                        dt}, this.GetPackingMeisaiOperationCompleted, userState);
        }
        
        private void OnGetPackingMeisaiOperationCompleted(object arg) {
            if ((this.GetPackingMeisaiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPackingMeisaiCompleted(this, new GetPackingMeisaiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetKiwakuKonpoTorokuData", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetKiwakuKonpoTorokuData(CondK02 cond, out string errMsgID, out string[] args) {
            object[] results = this.Invoke("GetKiwakuKonpoTorokuData", new object[] {
                        cond});
            errMsgID = ((string)(results[1]));
            args = ((string[])(results[2]));
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetKiwakuKonpoTorokuDataAsync(CondK02 cond) {
            this.GetKiwakuKonpoTorokuDataAsync(cond, null);
        }
        
        /// <remarks/>
        public void GetKiwakuKonpoTorokuDataAsync(CondK02 cond, object userState) {
            if ((this.GetKiwakuKonpoTorokuDataOperationCompleted == null)) {
                this.GetKiwakuKonpoTorokuDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetKiwakuKonpoTorokuDataOperationCompleted);
            }
            this.InvokeAsync("GetKiwakuKonpoTorokuData", new object[] {
                        cond}, this.GetKiwakuKonpoTorokuDataOperationCompleted, userState);
        }
        
        private void OnGetKiwakuKonpoTorokuDataOperationCompleted(object arg) {
            if ((this.GetKiwakuKonpoTorokuDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetKiwakuKonpoTorokuDataCompleted(this, new GetKiwakuKonpoTorokuDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/CheckKiwakuKonpoTorokuEdit", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CheckKiwakuKonpoTorokuEdit(CondK02 cond, out string errMsgID, out string[] args) {
            object[] results = this.Invoke("CheckKiwakuKonpoTorokuEdit", new object[] {
                        cond});
            errMsgID = ((string)(results[1]));
            args = ((string[])(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CheckKiwakuKonpoTorokuEditAsync(CondK02 cond) {
            this.CheckKiwakuKonpoTorokuEditAsync(cond, null);
        }
        
        /// <remarks/>
        public void CheckKiwakuKonpoTorokuEditAsync(CondK02 cond, object userState) {
            if ((this.CheckKiwakuKonpoTorokuEditOperationCompleted == null)) {
                this.CheckKiwakuKonpoTorokuEditOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckKiwakuKonpoTorokuEditOperationCompleted);
            }
            this.InvokeAsync("CheckKiwakuKonpoTorokuEdit", new object[] {
                        cond}, this.CheckKiwakuKonpoTorokuEditOperationCompleted, userState);
        }
        
        private void OnCheckKiwakuKonpoTorokuEditOperationCompleted(object arg) {
            if ((this.CheckKiwakuKonpoTorokuEditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckKiwakuKonpoTorokuEditCompleted(this, new CheckKiwakuKonpoTorokuEditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/UpdKiwakuKonpoToroku", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdKiwakuKonpoToroku(CondK02 cond, out string errMsgID, out string[] args) {
            object[] results = this.Invoke("UpdKiwakuKonpoToroku", new object[] {
                        cond});
            errMsgID = ((string)(results[1]));
            args = ((string[])(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdKiwakuKonpoTorokuAsync(CondK02 cond) {
            this.UpdKiwakuKonpoTorokuAsync(cond, null);
        }
        
        /// <remarks/>
        public void UpdKiwakuKonpoTorokuAsync(CondK02 cond, object userState) {
            if ((this.UpdKiwakuKonpoTorokuOperationCompleted == null)) {
                this.UpdKiwakuKonpoTorokuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdKiwakuKonpoTorokuOperationCompleted);
            }
            this.InvokeAsync("UpdKiwakuKonpoToroku", new object[] {
                        cond}, this.UpdKiwakuKonpoTorokuOperationCompleted, userState);
        }
        
        private void OnUpdKiwakuKonpoTorokuOperationCompleted(object arg) {
            if ((this.UpdKiwakuKonpoTorokuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdKiwakuKonpoTorokuCompleted(this, new UpdKiwakuKonpoTorokuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetKiwakuKonpoMeisaiData", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetKiwakuKonpoMeisaiData(CondK02 cond, out string errMsgID, out string[] args) {
            object[] results = this.Invoke("GetKiwakuKonpoMeisaiData", new object[] {
                        cond});
            errMsgID = ((string)(results[1]));
            args = ((string[])(results[2]));
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetKiwakuKonpoMeisaiDataAsync(CondK02 cond) {
            this.GetKiwakuKonpoMeisaiDataAsync(cond, null);
        }
        
        /// <remarks/>
        public void GetKiwakuKonpoMeisaiDataAsync(CondK02 cond, object userState) {
            if ((this.GetKiwakuKonpoMeisaiDataOperationCompleted == null)) {
                this.GetKiwakuKonpoMeisaiDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetKiwakuKonpoMeisaiDataOperationCompleted);
            }
            this.InvokeAsync("GetKiwakuKonpoMeisaiData", new object[] {
                        cond}, this.GetKiwakuKonpoMeisaiDataOperationCompleted, userState);
        }
        
        private void OnGetKiwakuKonpoMeisaiDataOperationCompleted(object arg) {
            if ((this.GetKiwakuKonpoMeisaiDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetKiwakuKonpoMeisaiDataCompleted(this, new GetKiwakuKonpoMeisaiDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetMoveShipData", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetMoveShipData(System.Data.DataSet ds, CondK02 cond, out string errMsgID, out string[] args) {
            object[] results = this.Invoke("GetMoveShipData", new object[] {
                        ds,
                        cond});
            errMsgID = ((string)(results[1]));
            args = ((string[])(results[2]));
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetMoveShipDataAsync(System.Data.DataSet ds, CondK02 cond) {
            this.GetMoveShipDataAsync(ds, cond, null);
        }
        
        /// <remarks/>
        public void GetMoveShipDataAsync(System.Data.DataSet ds, CondK02 cond, object userState) {
            if ((this.GetMoveShipDataOperationCompleted == null)) {
                this.GetMoveShipDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMoveShipDataOperationCompleted);
            }
            this.InvokeAsync("GetMoveShipData", new object[] {
                        ds,
                        cond}, this.GetMoveShipDataOperationCompleted, userState);
        }
        
        private void OnGetMoveShipDataOperationCompleted(object arg) {
            if ((this.GetMoveShipDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMoveShipDataCompleted(this, new GetMoveShipDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetKiwakuKonpoShukkaMeisaiFirstRowData", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetKiwakuKonpoShukkaMeisaiFirstRowData(CondK02 cond) {
            object[] results = this.Invoke("GetKiwakuKonpoShukkaMeisaiFirstRowData", new object[] {
                        cond});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetKiwakuKonpoShukkaMeisaiFirstRowDataAsync(CondK02 cond) {
            this.GetKiwakuKonpoShukkaMeisaiFirstRowDataAsync(cond, null);
        }
        
        /// <remarks/>
        public void GetKiwakuKonpoShukkaMeisaiFirstRowDataAsync(CondK02 cond, object userState) {
            if ((this.GetKiwakuKonpoShukkaMeisaiFirstRowDataOperationCompleted == null)) {
                this.GetKiwakuKonpoShukkaMeisaiFirstRowDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetKiwakuKonpoShukkaMeisaiFirstRowDataOperationCompleted);
            }
            this.InvokeAsync("GetKiwakuKonpoShukkaMeisaiFirstRowData", new object[] {
                        cond}, this.GetKiwakuKonpoShukkaMeisaiFirstRowDataOperationCompleted, userState);
        }
        
        private void OnGetKiwakuKonpoShukkaMeisaiFirstRowDataOperationCompleted(object arg) {
            if ((this.GetKiwakuKonpoShukkaMeisaiFirstRowDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetKiwakuKonpoShukkaMeisaiFirstRowDataCompleted(this, new GetKiwakuKonpoShukkaMeisaiFirstRowDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/UpdKiwakuKonpoMeisaiToroku", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdKiwakuKonpoMeisaiToroku(System.Data.DataSet ds, CondK02 cond, out string errMsgID, out string[] args) {
            object[] results = this.Invoke("UpdKiwakuKonpoMeisaiToroku", new object[] {
                        ds,
                        cond});
            errMsgID = ((string)(results[1]));
            args = ((string[])(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdKiwakuKonpoMeisaiTorokuAsync(System.Data.DataSet ds, CondK02 cond) {
            this.UpdKiwakuKonpoMeisaiTorokuAsync(ds, cond, null);
        }
        
        /// <remarks/>
        public void UpdKiwakuKonpoMeisaiTorokuAsync(System.Data.DataSet ds, CondK02 cond, object userState) {
            if ((this.UpdKiwakuKonpoMeisaiTorokuOperationCompleted == null)) {
                this.UpdKiwakuKonpoMeisaiTorokuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdKiwakuKonpoMeisaiTorokuOperationCompleted);
            }
            this.InvokeAsync("UpdKiwakuKonpoMeisaiToroku", new object[] {
                        ds,
                        cond}, this.UpdKiwakuKonpoMeisaiTorokuOperationCompleted, userState);
        }
        
        private void OnUpdKiwakuKonpoMeisaiTorokuOperationCompleted(object arg) {
            if ((this.UpdKiwakuKonpoMeisaiTorokuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdKiwakuKonpoMeisaiTorokuCompleted(this, new UpdKiwakuKonpoMeisaiTorokuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetKiwakuMatomeData", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetKiwakuMatomeData(CondK02 cond, out string errMsgID, out string[] args) {
            object[] results = this.Invoke("GetKiwakuMatomeData", new object[] {
                        cond});
            errMsgID = ((string)(results[1]));
            args = ((string[])(results[2]));
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetKiwakuMatomeDataAsync(CondK02 cond) {
            this.GetKiwakuMatomeDataAsync(cond, null);
        }
        
        /// <remarks/>
        public void GetKiwakuMatomeDataAsync(CondK02 cond, object userState) {
            if ((this.GetKiwakuMatomeDataOperationCompleted == null)) {
                this.GetKiwakuMatomeDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetKiwakuMatomeDataOperationCompleted);
            }
            this.InvokeAsync("GetKiwakuMatomeData", new object[] {
                        cond}, this.GetKiwakuMatomeDataOperationCompleted, userState);
        }
        
        private void OnGetKiwakuMatomeDataOperationCompleted(object arg) {
            if ((this.GetKiwakuMatomeDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetKiwakuMatomeDataCompleted(this, new GetKiwakuMatomeDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetMatomePackingMeisai", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetMatomePackingMeisai(CondK02 cond, System.Data.DataTable dt) {
            object[] results = this.Invoke("GetMatomePackingMeisai", new object[] {
                        cond,
                        dt});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetMatomePackingMeisaiAsync(CondK02 cond, System.Data.DataTable dt) {
            this.GetMatomePackingMeisaiAsync(cond, dt, null);
        }
        
        /// <remarks/>
        public void GetMatomePackingMeisaiAsync(CondK02 cond, System.Data.DataTable dt, object userState) {
            if ((this.GetMatomePackingMeisaiOperationCompleted == null)) {
                this.GetMatomePackingMeisaiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMatomePackingMeisaiOperationCompleted);
            }
            this.InvokeAsync("GetMatomePackingMeisai", new object[] {
                        cond,
                        dt}, this.GetMatomePackingMeisaiOperationCompleted, userState);
        }
        
        private void OnGetMatomePackingMeisaiOperationCompleted(object arg) {
            if ((this.GetMatomePackingMeisaiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMatomePackingMeisaiCompleted(this, new GetMatomePackingMeisaiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/SendCondBase", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendCondBase(CondBase cond) {
            this.Invoke("SendCondBase", new object[] {
                        cond});
        }
        
        /// <remarks/>
        public void SendCondBaseAsync(CondBase cond) {
            this.SendCondBaseAsync(cond, null);
        }
        
        /// <remarks/>
        public void SendCondBaseAsync(CondBase cond, object userState) {
            if ((this.SendCondBaseOperationCompleted == null)) {
                this.SendCondBaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendCondBaseOperationCompleted);
            }
            this.InvokeAsync("SendCondBase", new object[] {
                        cond}, this.SendCondBaseOperationCompleted, userState);
        }
        
        private void OnSendCondBaseOperationCompleted(object arg) {
            if ((this.SendCondBaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendCondBaseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9149")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smssrv/")]
    public partial class CondK02 : CondBase {
        
        private string saibanFlagField;
        
        private int countField;
        
        private bool isPreviewField;
        
        private string kojiNameField;
        
        private string shipField;
        
        private string hakkoSelectField;
        
        private string torokuFlagField;
        
        private string kojiNoField;
        
        private string caseIDField;
        
        private string sagyoFlagField;
        
        private string boxNoField;
        
        private string palletNoField;
        
        private string shukkaFlagField;
        
        private string nonyusakiCDField;
        
        private string tagNoField;
        
        private string aRNoField;
        
        private string kiwakuKonpoMoveShipFlagField;
        
        private string kiwakuNonyusakiCDField;
        
        private string kiwakuInsertTypeField;
        
        /// <remarks/>
        public string SaibanFlag {
            get {
                return this.saibanFlagField;
            }
            set {
                this.saibanFlagField = value;
            }
        }
        
        /// <remarks/>
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public bool IsPreview {
            get {
                return this.isPreviewField;
            }
            set {
                this.isPreviewField = value;
            }
        }
        
        /// <remarks/>
        public string KojiName {
            get {
                return this.kojiNameField;
            }
            set {
                this.kojiNameField = value;
            }
        }
        
        /// <remarks/>
        public string Ship {
            get {
                return this.shipField;
            }
            set {
                this.shipField = value;
            }
        }
        
        /// <remarks/>
        public string HakkoSelect {
            get {
                return this.hakkoSelectField;
            }
            set {
                this.hakkoSelectField = value;
            }
        }
        
        /// <remarks/>
        public string TorokuFlag {
            get {
                return this.torokuFlagField;
            }
            set {
                this.torokuFlagField = value;
            }
        }
        
        /// <remarks/>
        public string KojiNo {
            get {
                return this.kojiNoField;
            }
            set {
                this.kojiNoField = value;
            }
        }
        
        /// <remarks/>
        public string CaseID {
            get {
                return this.caseIDField;
            }
            set {
                this.caseIDField = value;
            }
        }
        
        /// <remarks/>
        public string SagyoFlag {
            get {
                return this.sagyoFlagField;
            }
            set {
                this.sagyoFlagField = value;
            }
        }
        
        /// <remarks/>
        public string BoxNo {
            get {
                return this.boxNoField;
            }
            set {
                this.boxNoField = value;
            }
        }
        
        /// <remarks/>
        public string PalletNo {
            get {
                return this.palletNoField;
            }
            set {
                this.palletNoField = value;
            }
        }
        
        /// <remarks/>
        public string ShukkaFlag {
            get {
                return this.shukkaFlagField;
            }
            set {
                this.shukkaFlagField = value;
            }
        }
        
        /// <remarks/>
        public string NonyusakiCD {
            get {
                return this.nonyusakiCDField;
            }
            set {
                this.nonyusakiCDField = value;
            }
        }
        
        /// <remarks/>
        public string TagNo {
            get {
                return this.tagNoField;
            }
            set {
                this.tagNoField = value;
            }
        }
        
        /// <remarks/>
        public string ARNo {
            get {
                return this.aRNoField;
            }
            set {
                this.aRNoField = value;
            }
        }
        
        /// <remarks/>
        public string KiwakuKonpoMoveShipFlag {
            get {
                return this.kiwakuKonpoMoveShipFlagField;
            }
            set {
                this.kiwakuKonpoMoveShipFlagField = value;
            }
        }
        
        /// <remarks/>
        public string KiwakuNonyusakiCD {
            get {
                return this.kiwakuNonyusakiCDField;
            }
            set {
                this.kiwakuNonyusakiCDField = value;
            }
        }
        
        /// <remarks/>
        public string KiwakuInsertType {
            get {
                return this.kiwakuInsertTypeField;
            }
            set {
                this.kiwakuInsertTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CondK02))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9149")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smssrv/")]
    public partial class CondBase {
        
        private LoginInfo loginInfoField;
        
        private object createDateField;
        
        private string createUserIDField;
        
        private string createUserNameField;
        
        private object updateDateField;
        
        private string updateUserIDField;
        
        private string updateUserNameField;
        
        private object mainteDateField;
        
        private string mainteUserIDField;
        
        private string mainteUserNameField;
        
        private string versionField;
        
        /// <remarks/>
        public LoginInfo LoginInfo {
            get {
                return this.loginInfoField;
            }
            set {
                this.loginInfoField = value;
            }
        }
        
        /// <remarks/>
        public object CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        public string CreateUserID {
            get {
                return this.createUserIDField;
            }
            set {
                this.createUserIDField = value;
            }
        }
        
        /// <remarks/>
        public string CreateUserName {
            get {
                return this.createUserNameField;
            }
            set {
                this.createUserNameField = value;
            }
        }
        
        /// <remarks/>
        public object UpdateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
            }
        }
        
        /// <remarks/>
        public string UpdateUserID {
            get {
                return this.updateUserIDField;
            }
            set {
                this.updateUserIDField = value;
            }
        }
        
        /// <remarks/>
        public string UpdateUserName {
            get {
                return this.updateUserNameField;
            }
            set {
                this.updateUserNameField = value;
            }
        }
        
        /// <remarks/>
        public object MainteDate {
            get {
                return this.mainteDateField;
            }
            set {
                this.mainteDateField = value;
            }
        }
        
        /// <remarks/>
        public string MainteUserID {
            get {
                return this.mainteUserIDField;
            }
            set {
                this.mainteUserIDField = value;
            }
        }
        
        /// <remarks/>
        public string MainteUserName {
            get {
                return this.mainteUserNameField;
            }
            set {
                this.mainteUserNameField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9149")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smssrv/")]
    public partial class LoginInfo {
        
        private string userIDField;
        
        private string userNameField;
        
        private string pcNameField;
        
        private string[] iPAddressField;
        
        private string roleIDField;
        
        private string roleNameField;
        
        private string languageField;
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string PcName {
            get {
                return this.pcNameField;
            }
            set {
                this.pcNameField = value;
            }
        }
        
        /// <remarks/>
        public string[] IPAddress {
            get {
                return this.iPAddressField;
            }
            set {
                this.iPAddressField = value;
            }
        }
        
        /// <remarks/>
        public string RoleID {
            get {
                return this.roleIDField;
            }
            set {
                this.roleIDField = value;
            }
        }
        
        /// <remarks/>
        public string RoleName {
            get {
                return this.roleNameField;
            }
            set {
                this.roleNameField = value;
            }
        }
        
        /// <remarks/>
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetNoListCompletedEventHandler(object sender, GetNoListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNoListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNoListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Data.DataTable noList {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string errorMsgID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetBoxListCompletedEventHandler(object sender, GetBoxListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBoxListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBoxListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetMeisaiCompletedEventHandler(object sender, GetMeisaiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMeisaiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMeisaiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetNonyusakiCompletedEventHandler(object sender, GetNonyusakiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNonyusakiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNonyusakiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void UpdBoxNoKanriCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetPalletListCompletedEventHandler(object sender, GetPalletListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPalletListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPalletListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetPalletNoCompletedEventHandler(object sender, GetPalletNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPalletNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPalletNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetBoxDataCompletedEventHandler(object sender, GetBoxDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBoxDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBoxDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void UpdPalletNoKanriCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetPackingListCompletedEventHandler(object sender, GetPackingListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPackingListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPackingListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetPackingMeisaiCompletedEventHandler(object sender, GetPackingMeisaiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPackingMeisaiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPackingMeisaiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetKiwakuKonpoTorokuDataCompletedEventHandler(object sender, GetKiwakuKonpoTorokuDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetKiwakuKonpoTorokuDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetKiwakuKonpoTorokuDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errMsgID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] args {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void CheckKiwakuKonpoTorokuEditCompletedEventHandler(object sender, CheckKiwakuKonpoTorokuEditCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckKiwakuKonpoTorokuEditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckKiwakuKonpoTorokuEditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errMsgID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] args {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void UpdKiwakuKonpoTorokuCompletedEventHandler(object sender, UpdKiwakuKonpoTorokuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdKiwakuKonpoTorokuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdKiwakuKonpoTorokuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errMsgID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] args {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetKiwakuKonpoMeisaiDataCompletedEventHandler(object sender, GetKiwakuKonpoMeisaiDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetKiwakuKonpoMeisaiDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetKiwakuKonpoMeisaiDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errMsgID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] args {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetMoveShipDataCompletedEventHandler(object sender, GetMoveShipDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMoveShipDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMoveShipDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errMsgID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] args {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetKiwakuKonpoShukkaMeisaiFirstRowDataCompletedEventHandler(object sender, GetKiwakuKonpoShukkaMeisaiFirstRowDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetKiwakuKonpoShukkaMeisaiFirstRowDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetKiwakuKonpoShukkaMeisaiFirstRowDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void UpdKiwakuKonpoMeisaiTorokuCompletedEventHandler(object sender, UpdKiwakuKonpoMeisaiTorokuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdKiwakuKonpoMeisaiTorokuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdKiwakuKonpoMeisaiTorokuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errMsgID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] args {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetKiwakuMatomeDataCompletedEventHandler(object sender, GetKiwakuMatomeDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetKiwakuMatomeDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetKiwakuMatomeDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errMsgID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] args {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetMatomePackingMeisaiCompletedEventHandler(object sender, GetMatomePackingMeisaiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMatomePackingMeisaiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMatomePackingMeisaiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void SendCondBaseCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591