//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.9179
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.K01.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMS.K01.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Area に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukaKaishi_Area {
            get {
                return ResourceManager.GetString("ShukaKaishi_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   集荷日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukaKaishi_AssemblyDate {
            get {
                return ResourceManager.GetString("ShukaKaishi_AssemblyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BoxNo. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukaKaishi_BoxNo {
            get {
                return ResourceManager.GetString("ShukaKaishi_BoxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CODE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukaKaishi_Code {
            get {
                return ResourceManager.GetString("ShukaKaishi_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通関確認状態 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukaKaishi_CustomsStatus {
            get {
                return ResourceManager.GetString("ShukaKaishi_CustomsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   図面追番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukaKaishi_DrawingAdditionalNo {
            get {
                return ResourceManager.GetString("ShukaKaishi_DrawingAdditionalNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   図番/形式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukaKaishi_DrawingNoFormat {
            get {
                return ResourceManager.GetString("ShukaKaishi_DrawingNoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Floor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukaKaishi_Floor {
            get {
                return ResourceManager.GetString("ShukaKaishi_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Free1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukaKaishi_Free1 {
            get {
                return ResourceManager.GetString("ShukaKaishi_Free1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Free2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukaKaishi_Free2 {
            get {
                return ResourceManager.GetString("ShukaKaishi_Free2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名(和文) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukaKaishi_JpName {
            get {
                return ResourceManager.GetString("ShukaKaishi_JpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Memo(備考) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukaKaishi_Memo {
            get {
                return ResourceManager.GetString("ShukaKaishi_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M-No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukaKaishi_MNo {
            get {
                return ResourceManager.GetString("ShukaKaishi_MNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   機種 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukaKaishi_Model {
            get {
                return ResourceManager.GetString("ShukaKaishi_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukaKaishi_Name {
            get {
                return ResourceManager.GetString("ShukaKaishi_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PalletNo. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukaKaishi_PalletNo {
            get {
                return ResourceManager.GetString("ShukaKaishi_PalletNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Print に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukaKaishi_Print {
            get {
                return ResourceManager.GetString("ShukaKaishi_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   製番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukaKaishi_ProductNo {
            get {
                return ResourceManager.GetString("ShukaKaishi_ProductNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukaKaishi_Quantity {
            get {
                return ResourceManager.GetString("ShukaKaishi_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   区割No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukaKaishi_SectioningNo {
            get {
                return ResourceManager.GetString("ShukaKaishi_SectioningNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷元 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukaKaishi_SipFromName {
            get {
                return ResourceManager.GetString("ShukaKaishi_SipFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   状態 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukaKaishi_State {
            get {
                return ResourceManager.GetString("ShukaKaishi_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ST-No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukaKaishi_STNo {
            get {
                return ResourceManager.GetString("ShukaKaishi_STNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tag No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukaKaishi_TagNo {
            get {
                return ResourceManager.GetString("ShukaKaishi_TagNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TAG便名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukaKaishi_TagShip {
            get {
                return ResourceManager.GetString("ShukaKaishi_TagShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   図番/形式2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukaKaishi_ZUMEN_KEISHIKI2 {
            get {
                return ResourceManager.GetString("ShukaKaishi_ZUMEN_KEISHIKI2", resourceCulture);
            }
        }
    }
}
