//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.9179
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.M01.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMS.M01.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Mail通知運用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BukkenMeiHoshu_MailNotificationInvestment {
            get {
                return ResourceManager.GetString("BukkenMeiHoshu_MailNotificationInvestment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   管理No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BukkenMeiHoshu_ManagementNo {
            get {
                return ResourceManager.GetString("BukkenMeiHoshu_ManagementNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   物件名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BukkenMeiHoshu_PropertyName {
            get {
                return ResourceManager.GetString("BukkenMeiHoshu_PropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BukkenMeiHoshu_ShippingDivision {
            get {
                return ResourceManager.GetString("BukkenMeiHoshu_ShippingDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷区分(非表示) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BukkenMeiHoshu_ShippingDivisionHidden {
            get {
                return ResourceManager.GetString("BukkenMeiHoshu_ShippingDivisionHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TAG数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BukkenMeiHoshu_TagNo {
            get {
                return ResourceManager.GetString("BukkenMeiHoshu_TagNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AR TAG数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BukkenMeiHoshuIkkatsu_ArTagNo {
            get {
                return ResourceManager.GetString("BukkenMeiHoshuIkkatsu_ArTagNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   物件名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BukkenMeiHoshuIkkatsu_BukkenName {
            get {
                return ResourceManager.GetString("BukkenMeiHoshuIkkatsu_BukkenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail通知運用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BukkenMeiHoshuIkkatsu_MailNotify {
            get {
                return ResourceManager.GetString("BukkenMeiHoshuIkkatsu_MailNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   本体 TAG数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BukkenMeiHoshuIkkatsu_NormalTagNo {
            get {
                return ResourceManager.GetString("BukkenMeiHoshuIkkatsu_NormalTagNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   受注No に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BukkenmeiHosyuIkkatsu_JuchuNo {
            get {
                return ResourceManager.GetString("BukkenmeiHosyuIkkatsu_JuchuNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AR No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EcsHoshu_ArNo {
            get {
                return ResourceManager.GetString("EcsHoshu_ArNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   物件名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EcsHoshu_BukkenName {
            get {
                return ResourceManager.GetString("EcsHoshu_BukkenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CODE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EcsHoshu_Code {
            get {
                return ResourceManager.GetString("EcsHoshu_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ECS No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EcsHoshu_EcsNo {
            get {
                return ResourceManager.GetString("EcsHoshu_EcsNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   管理区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EcsHoshu_KanriFlag {
            get {
                return ResourceManager.GetString("EcsHoshu_KanriFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   機種 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EcsHoshu_Kishu {
            get {
                return ResourceManager.GetString("EcsHoshu_Kishu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   期 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EcsHoshu_Quota {
            get {
                return ResourceManager.GetString("EcsHoshu_Quota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   製番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EcsHoshu_Seiban {
            get {
                return ResourceManager.GetString("EcsHoshu_Seiban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   住所 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HaisosakiHoshu_Address {
            get {
                return ResourceManager.GetString("HaisosakiHoshu_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAX に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HaisosakiHoshu_Fax {
            get {
                return ResourceManager.GetString("HaisosakiHoshu_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HaisosakiHoshu_Name {
            get {
                return ResourceManager.GetString("HaisosakiHoshu_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExcelFiles|*.xlsx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HaisosakiHoshu_sdfExcel_Filter {
            get {
                return ResourceManager.GetString("HaisosakiHoshu_sdfExcel_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %DESKTOP% に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HaisosakiHoshu_sdfExcel_InitialDirectory {
            get {
                return ResourceManager.GetString("HaisosakiHoshu_sdfExcel_InitialDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配送先ExcelFiles保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HaisosakiHoshu_sdfExcel_Title {
            get {
                return ResourceManager.GetString("HaisosakiHoshu_sdfExcel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷先担当者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HaisosakiHoshu_ShippingContact {
            get {
                return ResourceManager.GetString("HaisosakiHoshu_ShippingContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷物 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HaisosakiHoshu_ShippingItem {
            get {
                return ResourceManager.GetString("HaisosakiHoshu_ShippingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HaisosakiHoshu_ShippingType {
            get {
                return ResourceManager.GetString("HaisosakiHoshu_ShippingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   並び順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HaisosakiHoshu_SortNo {
            get {
                return ResourceManager.GetString("HaisosakiHoshu_SortNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TEL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HaisosakiHoshu_Tel1 {
            get {
                return ResourceManager.GetString("HaisosakiHoshu_Tel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TEL(2) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HaisosakiHoshu_Tel2 {
            get {
                return ResourceManager.GetString("HaisosakiHoshu_Tel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   受取不可日8月連休 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HaisosakiHoshu_UnavailAug {
            get {
                return ResourceManager.GetString("HaisosakiHoshu_UnavailAug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   受取不可日5月連休 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HaisosakiHoshu_UnavailMay {
            get {
                return ResourceManager.GetString("HaisosakiHoshu_UnavailMay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   受取不可日通常 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HaisosakiHoshu_UnavailNorm {
            get {
                return ResourceManager.GetString("HaisosakiHoshu_UnavailNorm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   受取不可日正月連休 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HaisosakiHoshu_UnavailNy {
            get {
                return ResourceManager.GetString("HaisosakiHoshu_UnavailNy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HaisousakidHosyu_Name {
            get {
                return ResourceManager.GetString("HaisousakidHosyu_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Area に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KonpoJohoHoshu_Area {
            get {
                return ResourceManager.GetString("KonpoJohoHoshu_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AR No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KonpoJohoHoshu_ARNo {
            get {
                return ResourceManager.GetString("KonpoJohoHoshu_ARNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BoxNo. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KonpoJohoHoshu_BoxNo {
            get {
                return ResourceManager.GetString("KonpoJohoHoshu_BoxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CODE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KonpoJohoHoshu_Code {
            get {
                return ResourceManager.GetString("KonpoJohoHoshu_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   図面追番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KonpoJohoHoshu_DrawingAdditionalNo {
            get {
                return ResourceManager.GetString("KonpoJohoHoshu_DrawingAdditionalNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   図番/形式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KonpoJohoHoshu_DrawingNoFormat {
            get {
                return ResourceManager.GetString("KonpoJohoHoshu_DrawingNoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Floor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KonpoJohoHoshu_Floor {
            get {
                return ResourceManager.GetString("KonpoJohoHoshu_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名(和文) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KonpoJohoHoshu_JpName {
            get {
                return ResourceManager.GetString("KonpoJohoHoshu_JpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Memo(備考) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KonpoJohoHoshu_Memo {
            get {
                return ResourceManager.GetString("KonpoJohoHoshu_Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   M-No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KonpoJohoHoshu_MNo {
            get {
                return ResourceManager.GetString("KonpoJohoHoshu_MNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   機種 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KonpoJohoHoshu_Model {
            get {
                return ResourceManager.GetString("KonpoJohoHoshu_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KonpoJohoHoshu_Name {
            get {
                return ResourceManager.GetString("KonpoJohoHoshu_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   製番 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KonpoJohoHoshu_ProductNo {
            get {
                return ResourceManager.GetString("KonpoJohoHoshu_ProductNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KonpoJohoHoshu_Quantity {
            get {
                return ResourceManager.GetString("KonpoJohoHoshu_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   区割No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KonpoJohoHoshu_SectioningNo {
            get {
                return ResourceManager.GetString("KonpoJohoHoshu_SectioningNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ST-No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KonpoJohoHoshu_STNo {
            get {
                return ResourceManager.GetString("KonpoJohoHoshu_STNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tag No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KonpoJohoHoshu_TagNo {
            get {
                return ResourceManager.GetString("KonpoJohoHoshu_TagNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CC に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MailSendInfo_Cc {
            get {
                return ResourceManager.GetString("MailSendInfo_Cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MailSendInfo_DateModified {
            get {
                return ResourceManager.GetString("MailSendInfo_DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   失敗回数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MailSendInfo_FailureCount {
            get {
                return ResourceManager.GetString("MailSendInfo_FailureCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   失敗理由 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MailSendInfo_FailureReason {
            get {
                return ResourceManager.GetString("MailSendInfo_FailureReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録日時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MailSendInfo_RegisterdDate {
            get {
                return ResourceManager.GetString("MailSendInfo_RegisterdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   状態 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MailSendInfo_State {
            get {
                return ResourceManager.GetString("MailSendInfo_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   件名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MailSendInfo_Subject {
            get {
                return ResourceManager.GetString("MailSendInfo_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TO に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MailSendInfo_To {
            get {
                return ResourceManager.GetString("MailSendInfo_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MeishoHoshu_Name {
            get {
                return ResourceManager.GetString("MeishoHoshu_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   住所 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NiukeHoshu_Address {
            get {
                return ResourceManager.GetString("NiukeHoshu_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中国向け に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NiukeHoshu_ChinaFlag {
            get {
                return ResourceManager.GetString("NiukeHoshu_ChinaFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FAX に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NiukeHoshu_Fax {
            get {
                return ResourceManager.GetString("NiukeHoshu_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NiukeHoshu_Name {
            get {
                return ResourceManager.GetString("NiukeHoshu_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   並び順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NiukeHoshu_SortNo {
            get {
                return ResourceManager.GetString("NiukeHoshu_SortNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TEL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NiukeHoshu_Tel1 {
            get {
                return ResourceManager.GetString("NiukeHoshu_Tel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TEL(2) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NiukeHoshu_Tel2 {
            get {
                return ResourceManager.GetString("NiukeHoshu_Tel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   USCI に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NiukeHoshu_UsciCd {
            get {
                return ResourceManager.GetString("NiukeHoshu_UsciCd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   納入先(User) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NonyusakiHoshu_DeliveryDestination {
            get {
                return ResourceManager.GetString("NonyusakiHoshu_DeliveryDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   除外区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NonyusakiHoshu_ExclusionDivision {
            get {
                return ResourceManager.GetString("NonyusakiHoshu_ExclusionDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   本体 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NonyusakiHoshu_FlagName {
            get {
                return ResourceManager.GetString("NonyusakiHoshu_FlagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   管理区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NonyusakiHoshu_ManagementDivision {
            get {
                return ResourceManager.GetString("NonyusakiHoshu_ManagementDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   管理No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NonyusakiHoshu_ManagementNo {
            get {
                return ResourceManager.GetString("NonyusakiHoshu_ManagementNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   便(Ship) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NonyusakiHoshu_Ship {
            get {
                return ResourceManager.GetString("NonyusakiHoshu_Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NonyusakiHoshu_ShippingDivision {
            get {
                return ResourceManager.GetString("NonyusakiHoshu_ShippingDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出荷元 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NounyusakiHoshu_SipFromName {
            get {
                return ResourceManager.GetString("NounyusakiHoshu_SipFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取引先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PartsNameHonyaku_Customer {
            get {
                return ResourceManager.GetString("PartsNameHonyaku_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通関確認状態 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PartsNameHonyaku_CustomsStatus {
            get {
                return ResourceManager.GetString("PartsNameHonyaku_CustomsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   INV付加名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PartsNameHonyaku_InvName {
            get {
                return ResourceManager.GetString("PartsNameHonyaku_InvName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名(和文) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PartsNameHonyaku_JPName {
            get {
                return ResourceManager.GetString("PartsNameHonyaku_JPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Maker に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PartsNameHonyaku_Maker {
            get {
                return ResourceManager.GetString("PartsNameHonyaku_Maker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PartsNameHonyaku_Name {
            get {
                return ResourceManager.GetString("PartsNameHonyaku_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   備考 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PartsNameHonyaku_Notes {
            get {
                return ResourceManager.GetString("PartsNameHonyaku_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数値が入力可能です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PartsNameHonyaku_Numeric {
            get {
                return ResourceManager.GetString("PartsNameHonyaku_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExcelFiles|*.xlsx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PartsNameHonyaku_ofdExcel_Filter {
            get {
                return ResourceManager.GetString("PartsNameHonyaku_ofdExcel_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filesを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PartsNameHonyaku_ofdExcel_Title {
            get {
                return ResourceManager.GetString("PartsNameHonyaku_ofdExcel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   原産国 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PartsNameHonyaku_OriginCountry {
            get {
                return ResourceManager.GetString("PartsNameHonyaku_OriginCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   環境依存文字は使用できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PartsNameHonyaku_PlatformDependentChar {
            get {
                return ResourceManager.GetString("PartsNameHonyaku_PlatformDependentChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExcelFiles|*.xlsx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PartsNameHonyaku_sdfExcel_Filter {
            get {
                return ResourceManager.GetString("PartsNameHonyaku_sdfExcel_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パーツ名翻訳ExcelFiles保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PartsNameHonyaku_sdfExcel_Title {
            get {
                return ResourceManager.GetString("PartsNameHonyaku_sdfExcel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   半角英数が入力可能です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PartsNameHonyaku_Singlebyte {
            get {
                return ResourceManager.GetString("PartsNameHonyaku_Singlebyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PartsNameHonyaku_Type {
            get {
                return ResourceManager.GetString("PartsNameHonyaku_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   英大文字、数値が入力可能です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PartsNameHonyaku_UpperAndNumber {
            get {
                return ResourceManager.GetString("PartsNameHonyaku_UpperAndNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   並び順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkamotoHoshu_DispNo {
            get {
                return ResourceManager.GetString("ShukkamotoHoshu_DispNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   社内外 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkamotoHoshu_ShanaiGaiFlag {
            get {
                return ResourceManager.GetString("ShukkamotoHoshu_ShanaiGaiFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkamotoHoshu_ShipFrom {
            get {
                return ResourceManager.GetString("ShukkamotoHoshu_ShipFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未使用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShukkamotoHoshu_UnusedFlag {
            get {
                return ResourceManager.GetString("ShukkamotoHoshu_UnusedFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invoice に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnsoKaisyaHoshu_InvoiceFlag {
            get {
                return ResourceManager.GetString("UnsoKaisyaHoshu_InvoiceFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   国内外 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnsoKaisyaHoshu_KokunaiGaiFlag {
            get {
                return ResourceManager.GetString("UnsoKaisyaHoshu_KokunaiGaiFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PackingList に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnsoKaisyaHoshu_PackingListFlag {
            get {
                return ResourceManager.GetString("UnsoKaisyaHoshu_PackingListFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   並び順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnsoKaisyaHoshu_SortNo {
            get {
                return ResourceManager.GetString("UnsoKaisyaHoshu_SortNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   輸出通関確認書宛先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnsoKaisyaHoshu_TuukanAttn {
            get {
                return ResourceManager.GetString("UnsoKaisyaHoshu_TuukanAttn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   輸出通関確認書 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnsoKaisyaHoshu_TuukanFlag {
            get {
                return ResourceManager.GetString("UnsoKaisyaHoshu_TuukanFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnsoKaisyaHoshu_UnsokaishaName {
            get {
                return ResourceManager.GetString("UnsoKaisyaHoshu_UnsokaishaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   管理No. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnsoKaisyaHoshu_UnsokaishaNo {
            get {
                return ResourceManager.GetString("UnsoKaisyaHoshu_UnsokaishaNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   権限 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserMaster_Authority {
            get {
                return ResourceManager.GetString("UserMaster_Authority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MailAddress変更権限 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserMaster_ChangeAuthority {
            get {
                return ResourceManager.GetString("UserMaster_ChangeAuthority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MailAddress に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserMaster_MailAddress {
            get {
                return ResourceManager.GetString("UserMaster_MailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   荷姿表送信対象 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserMaster_MailPackingFlag {
            get {
                return ResourceManager.GetString("UserMaster_MailPackingFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   計画取込一括設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserMaster_MailShukkakeikakuFlag {
            get {
                return ResourceManager.GetString("UserMaster_MailShukkakeikakuFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TAG連携送信対象 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserMaster_MailTagRenkeiFlag {
            get {
                return ResourceManager.GetString("UserMaster_MailTagRenkeiFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   備考 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserMaster_Remarks {
            get {
                return ResourceManager.GetString("UserMaster_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ExcelFiles|*.xlsx に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserMaster_sdfExcel_Filter {
            get {
                return ResourceManager.GetString("UserMaster_sdfExcel_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   担当者ExcelFiles保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserMaster_sdfExcel_Title {
            get {
                return ResourceManager.GetString("UserMaster_sdfExcel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   担当者Code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserMaster_StaffCode {
            get {
                return ResourceManager.GetString("UserMaster_StaffCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Staff区分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserMaster_StaffKbn {
            get {
                return ResourceManager.GetString("UserMaster_StaffKbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   担当者Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UserMaster_StaffName {
            get {
                return ResourceManager.GetString("UserMaster_StaffName", resourceCulture);
            }
        }
    }
}
