//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.9174
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// このソース コードは Microsoft.VSDesigner、バージョン 2.0.50727.9174 によって自動生成されました。
// 
#pragma warning disable 1591

namespace WsConnection.WebRefS02 {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsS02Soap", Namespace="http://smssrv/")]
    public partial class WsS02 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetBoxDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPalletDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetKiwakuDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdBoxDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdPalletDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdKiwakuDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBoxMeisaiOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetShukkaMeisaiOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetConsignOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDeliverOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNisugataOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckInvoiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdShippingDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetShippingDocumentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTyouhyouDataDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTyouhyouDataEOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTyouhyouDataGOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTyouhyouDataHOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendCondBaseOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsS02() {
            this.Url = global::WsConnection.Properties.Settings.Default.WsConnection_WebRefS02_WsS02;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetBoxDataCompletedEventHandler GetBoxDataCompleted;
        
        /// <remarks/>
        public event GetPalletDataCompletedEventHandler GetPalletDataCompleted;
        
        /// <remarks/>
        public event GetKiwakuDataCompletedEventHandler GetKiwakuDataCompleted;
        
        /// <remarks/>
        public event UpdBoxDataCompletedEventHandler UpdBoxDataCompleted;
        
        /// <remarks/>
        public event UpdPalletDataCompletedEventHandler UpdPalletDataCompleted;
        
        /// <remarks/>
        public event UpdKiwakuDataCompletedEventHandler UpdKiwakuDataCompleted;
        
        /// <remarks/>
        public event GetBoxMeisaiCompletedEventHandler GetBoxMeisaiCompleted;
        
        /// <remarks/>
        public event GetShukkaMeisaiCompletedEventHandler GetShukkaMeisaiCompleted;
        
        /// <remarks/>
        public event GetConsignCompletedEventHandler GetConsignCompleted;
        
        /// <remarks/>
        public event GetDeliverCompletedEventHandler GetDeliverCompleted;
        
        /// <remarks/>
        public event GetNisugataCompletedEventHandler GetNisugataCompleted;
        
        /// <remarks/>
        public event CheckInvoiceCompletedEventHandler CheckInvoiceCompleted;
        
        /// <remarks/>
        public event UpdShippingDataCompletedEventHandler UpdShippingDataCompleted;
        
        /// <remarks/>
        public event GetShippingDocumentCompletedEventHandler GetShippingDocumentCompleted;
        
        /// <remarks/>
        public event GetTyouhyouDataDCompletedEventHandler GetTyouhyouDataDCompleted;
        
        /// <remarks/>
        public event GetTyouhyouDataECompletedEventHandler GetTyouhyouDataECompleted;
        
        /// <remarks/>
        public event GetTyouhyouDataGCompletedEventHandler GetTyouhyouDataGCompleted;
        
        /// <remarks/>
        public event GetTyouhyouDataHCompletedEventHandler GetTyouhyouDataHCompleted;
        
        /// <remarks/>
        public event SendCondBaseCompletedEventHandler SendCondBaseCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetBoxData", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetBoxData(CondS02 cond, out string errMsgID, out string[] args) {
            object[] results = this.Invoke("GetBoxData", new object[] {
                        cond});
            errMsgID = ((string)(results[1]));
            args = ((string[])(results[2]));
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetBoxDataAsync(CondS02 cond) {
            this.GetBoxDataAsync(cond, null);
        }
        
        /// <remarks/>
        public void GetBoxDataAsync(CondS02 cond, object userState) {
            if ((this.GetBoxDataOperationCompleted == null)) {
                this.GetBoxDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBoxDataOperationCompleted);
            }
            this.InvokeAsync("GetBoxData", new object[] {
                        cond}, this.GetBoxDataOperationCompleted, userState);
        }
        
        private void OnGetBoxDataOperationCompleted(object arg) {
            if ((this.GetBoxDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBoxDataCompleted(this, new GetBoxDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetPalletData", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetPalletData(CondS02 cond, out string errMsgID, out string[] args) {
            object[] results = this.Invoke("GetPalletData", new object[] {
                        cond});
            errMsgID = ((string)(results[1]));
            args = ((string[])(results[2]));
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetPalletDataAsync(CondS02 cond) {
            this.GetPalletDataAsync(cond, null);
        }
        
        /// <remarks/>
        public void GetPalletDataAsync(CondS02 cond, object userState) {
            if ((this.GetPalletDataOperationCompleted == null)) {
                this.GetPalletDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPalletDataOperationCompleted);
            }
            this.InvokeAsync("GetPalletData", new object[] {
                        cond}, this.GetPalletDataOperationCompleted, userState);
        }
        
        private void OnGetPalletDataOperationCompleted(object arg) {
            if ((this.GetPalletDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPalletDataCompleted(this, new GetPalletDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetKiwakuData", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetKiwakuData(CondS02 cond, out string errMsgID, out string[] args) {
            object[] results = this.Invoke("GetKiwakuData", new object[] {
                        cond});
            errMsgID = ((string)(results[1]));
            args = ((string[])(results[2]));
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetKiwakuDataAsync(CondS02 cond) {
            this.GetKiwakuDataAsync(cond, null);
        }
        
        /// <remarks/>
        public void GetKiwakuDataAsync(CondS02 cond, object userState) {
            if ((this.GetKiwakuDataOperationCompleted == null)) {
                this.GetKiwakuDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetKiwakuDataOperationCompleted);
            }
            this.InvokeAsync("GetKiwakuData", new object[] {
                        cond}, this.GetKiwakuDataOperationCompleted, userState);
        }
        
        private void OnGetKiwakuDataOperationCompleted(object arg) {
            if ((this.GetKiwakuDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetKiwakuDataCompleted(this, new GetKiwakuDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/UpdBoxData", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdBoxData(CondS02 cond, System.Data.DataTable dt, out string errMsgID, out string[] args) {
            object[] results = this.Invoke("UpdBoxData", new object[] {
                        cond,
                        dt});
            errMsgID = ((string)(results[1]));
            args = ((string[])(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdBoxDataAsync(CondS02 cond, System.Data.DataTable dt) {
            this.UpdBoxDataAsync(cond, dt, null);
        }
        
        /// <remarks/>
        public void UpdBoxDataAsync(CondS02 cond, System.Data.DataTable dt, object userState) {
            if ((this.UpdBoxDataOperationCompleted == null)) {
                this.UpdBoxDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdBoxDataOperationCompleted);
            }
            this.InvokeAsync("UpdBoxData", new object[] {
                        cond,
                        dt}, this.UpdBoxDataOperationCompleted, userState);
        }
        
        private void OnUpdBoxDataOperationCompleted(object arg) {
            if ((this.UpdBoxDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdBoxDataCompleted(this, new UpdBoxDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/UpdPalletData", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdPalletData(CondS02 cond, System.Data.DataTable dt, out string errMsgID, out string[] args) {
            object[] results = this.Invoke("UpdPalletData", new object[] {
                        cond,
                        dt});
            errMsgID = ((string)(results[1]));
            args = ((string[])(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdPalletDataAsync(CondS02 cond, System.Data.DataTable dt) {
            this.UpdPalletDataAsync(cond, dt, null);
        }
        
        /// <remarks/>
        public void UpdPalletDataAsync(CondS02 cond, System.Data.DataTable dt, object userState) {
            if ((this.UpdPalletDataOperationCompleted == null)) {
                this.UpdPalletDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdPalletDataOperationCompleted);
            }
            this.InvokeAsync("UpdPalletData", new object[] {
                        cond,
                        dt}, this.UpdPalletDataOperationCompleted, userState);
        }
        
        private void OnUpdPalletDataOperationCompleted(object arg) {
            if ((this.UpdPalletDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdPalletDataCompleted(this, new UpdPalletDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/UpdKiwakuData", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdKiwakuData(CondS02 cond, System.Data.DataTable dt, out string errMsgID, out string[] args) {
            object[] results = this.Invoke("UpdKiwakuData", new object[] {
                        cond,
                        dt});
            errMsgID = ((string)(results[1]));
            args = ((string[])(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdKiwakuDataAsync(CondS02 cond, System.Data.DataTable dt) {
            this.UpdKiwakuDataAsync(cond, dt, null);
        }
        
        /// <remarks/>
        public void UpdKiwakuDataAsync(CondS02 cond, System.Data.DataTable dt, object userState) {
            if ((this.UpdKiwakuDataOperationCompleted == null)) {
                this.UpdKiwakuDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdKiwakuDataOperationCompleted);
            }
            this.InvokeAsync("UpdKiwakuData", new object[] {
                        cond,
                        dt}, this.UpdKiwakuDataOperationCompleted, userState);
        }
        
        private void OnUpdKiwakuDataOperationCompleted(object arg) {
            if ((this.UpdKiwakuDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdKiwakuDataCompleted(this, new UpdKiwakuDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetBoxMeisai", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetBoxMeisai(CondS02 cond) {
            object[] results = this.Invoke("GetBoxMeisai", new object[] {
                        cond});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetBoxMeisaiAsync(CondS02 cond) {
            this.GetBoxMeisaiAsync(cond, null);
        }
        
        /// <remarks/>
        public void GetBoxMeisaiAsync(CondS02 cond, object userState) {
            if ((this.GetBoxMeisaiOperationCompleted == null)) {
                this.GetBoxMeisaiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBoxMeisaiOperationCompleted);
            }
            this.InvokeAsync("GetBoxMeisai", new object[] {
                        cond}, this.GetBoxMeisaiOperationCompleted, userState);
        }
        
        private void OnGetBoxMeisaiOperationCompleted(object arg) {
            if ((this.GetBoxMeisaiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBoxMeisaiCompleted(this, new GetBoxMeisaiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetShukkaMeisai", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetShukkaMeisai(CondS02 cond, out string errMsgID, out string[] args) {
            object[] results = this.Invoke("GetShukkaMeisai", new object[] {
                        cond});
            errMsgID = ((string)(results[1]));
            args = ((string[])(results[2]));
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetShukkaMeisaiAsync(CondS02 cond) {
            this.GetShukkaMeisaiAsync(cond, null);
        }
        
        /// <remarks/>
        public void GetShukkaMeisaiAsync(CondS02 cond, object userState) {
            if ((this.GetShukkaMeisaiOperationCompleted == null)) {
                this.GetShukkaMeisaiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetShukkaMeisaiOperationCompleted);
            }
            this.InvokeAsync("GetShukkaMeisai", new object[] {
                        cond}, this.GetShukkaMeisaiOperationCompleted, userState);
        }
        
        private void OnGetShukkaMeisaiOperationCompleted(object arg) {
            if ((this.GetShukkaMeisaiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetShukkaMeisaiCompleted(this, new GetShukkaMeisaiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetConsign", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetConsign(CondS02 cond) {
            object[] results = this.Invoke("GetConsign", new object[] {
                        cond});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetConsignAsync(CondS02 cond) {
            this.GetConsignAsync(cond, null);
        }
        
        /// <remarks/>
        public void GetConsignAsync(CondS02 cond, object userState) {
            if ((this.GetConsignOperationCompleted == null)) {
                this.GetConsignOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetConsignOperationCompleted);
            }
            this.InvokeAsync("GetConsign", new object[] {
                        cond}, this.GetConsignOperationCompleted, userState);
        }
        
        private void OnGetConsignOperationCompleted(object arg) {
            if ((this.GetConsignCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetConsignCompleted(this, new GetConsignCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetDeliver", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetDeliver(CondS02 cond) {
            object[] results = this.Invoke("GetDeliver", new object[] {
                        cond});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetDeliverAsync(CondS02 cond) {
            this.GetDeliverAsync(cond, null);
        }
        
        /// <remarks/>
        public void GetDeliverAsync(CondS02 cond, object userState) {
            if ((this.GetDeliverOperationCompleted == null)) {
                this.GetDeliverOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDeliverOperationCompleted);
            }
            this.InvokeAsync("GetDeliver", new object[] {
                        cond}, this.GetDeliverOperationCompleted, userState);
        }
        
        private void OnGetDeliverOperationCompleted(object arg) {
            if ((this.GetDeliverCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDeliverCompleted(this, new GetDeliverCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetNisugata", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetNisugata(CondS02 cond) {
            object[] results = this.Invoke("GetNisugata", new object[] {
                        cond});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetNisugataAsync(CondS02 cond) {
            this.GetNisugataAsync(cond, null);
        }
        
        /// <remarks/>
        public void GetNisugataAsync(CondS02 cond, object userState) {
            if ((this.GetNisugataOperationCompleted == null)) {
                this.GetNisugataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNisugataOperationCompleted);
            }
            this.InvokeAsync("GetNisugata", new object[] {
                        cond}, this.GetNisugataOperationCompleted, userState);
        }
        
        private void OnGetNisugataOperationCompleted(object arg) {
            if ((this.GetNisugataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNisugataCompleted(this, new GetNisugataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/CheckInvoice", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable CheckInvoice(CondS02 cond, System.Data.DataTable dt) {
            object[] results = this.Invoke("CheckInvoice", new object[] {
                        cond,
                        dt});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void CheckInvoiceAsync(CondS02 cond, System.Data.DataTable dt) {
            this.CheckInvoiceAsync(cond, dt, null);
        }
        
        /// <remarks/>
        public void CheckInvoiceAsync(CondS02 cond, System.Data.DataTable dt, object userState) {
            if ((this.CheckInvoiceOperationCompleted == null)) {
                this.CheckInvoiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckInvoiceOperationCompleted);
            }
            this.InvokeAsync("CheckInvoice", new object[] {
                        cond,
                        dt}, this.CheckInvoiceOperationCompleted, userState);
        }
        
        private void OnCheckInvoiceOperationCompleted(object arg) {
            if ((this.CheckInvoiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckInvoiceCompleted(this, new CheckInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/UpdShippingData", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdShippingData(CondS02 cond, System.Data.DataTable dt, out string errMsgID, out string[] args) {
            object[] results = this.Invoke("UpdShippingData", new object[] {
                        cond,
                        dt});
            errMsgID = ((string)(results[1]));
            args = ((string[])(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdShippingDataAsync(CondS02 cond, System.Data.DataTable dt) {
            this.UpdShippingDataAsync(cond, dt, null);
        }
        
        /// <remarks/>
        public void UpdShippingDataAsync(CondS02 cond, System.Data.DataTable dt, object userState) {
            if ((this.UpdShippingDataOperationCompleted == null)) {
                this.UpdShippingDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdShippingDataOperationCompleted);
            }
            this.InvokeAsync("UpdShippingData", new object[] {
                        cond,
                        dt}, this.UpdShippingDataOperationCompleted, userState);
        }
        
        private void OnUpdShippingDataOperationCompleted(object arg) {
            if ((this.UpdShippingDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdShippingDataCompleted(this, new UpdShippingDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetShippingDocument", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetShippingDocument(CondS02 cond) {
            object[] results = this.Invoke("GetShippingDocument", new object[] {
                        cond});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetShippingDocumentAsync(CondS02 cond) {
            this.GetShippingDocumentAsync(cond, null);
        }
        
        /// <remarks/>
        public void GetShippingDocumentAsync(CondS02 cond, object userState) {
            if ((this.GetShippingDocumentOperationCompleted == null)) {
                this.GetShippingDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetShippingDocumentOperationCompleted);
            }
            this.InvokeAsync("GetShippingDocument", new object[] {
                        cond}, this.GetShippingDocumentOperationCompleted, userState);
        }
        
        private void OnGetShippingDocumentOperationCompleted(object arg) {
            if ((this.GetShippingDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetShippingDocumentCompleted(this, new GetShippingDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetTyouhyouDataD", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetTyouhyouDataD(CondS02 cond) {
            object[] results = this.Invoke("GetTyouhyouDataD", new object[] {
                        cond});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetTyouhyouDataDAsync(CondS02 cond) {
            this.GetTyouhyouDataDAsync(cond, null);
        }
        
        /// <remarks/>
        public void GetTyouhyouDataDAsync(CondS02 cond, object userState) {
            if ((this.GetTyouhyouDataDOperationCompleted == null)) {
                this.GetTyouhyouDataDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTyouhyouDataDOperationCompleted);
            }
            this.InvokeAsync("GetTyouhyouDataD", new object[] {
                        cond}, this.GetTyouhyouDataDOperationCompleted, userState);
        }
        
        private void OnGetTyouhyouDataDOperationCompleted(object arg) {
            if ((this.GetTyouhyouDataDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTyouhyouDataDCompleted(this, new GetTyouhyouDataDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetTyouhyouDataE", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetTyouhyouDataE(CondS02 cond) {
            object[] results = this.Invoke("GetTyouhyouDataE", new object[] {
                        cond});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetTyouhyouDataEAsync(CondS02 cond) {
            this.GetTyouhyouDataEAsync(cond, null);
        }
        
        /// <remarks/>
        public void GetTyouhyouDataEAsync(CondS02 cond, object userState) {
            if ((this.GetTyouhyouDataEOperationCompleted == null)) {
                this.GetTyouhyouDataEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTyouhyouDataEOperationCompleted);
            }
            this.InvokeAsync("GetTyouhyouDataE", new object[] {
                        cond}, this.GetTyouhyouDataEOperationCompleted, userState);
        }
        
        private void OnGetTyouhyouDataEOperationCompleted(object arg) {
            if ((this.GetTyouhyouDataECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTyouhyouDataECompleted(this, new GetTyouhyouDataECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetTyouhyouDataG", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetTyouhyouDataG(CondS02 cond) {
            object[] results = this.Invoke("GetTyouhyouDataG", new object[] {
                        cond});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetTyouhyouDataGAsync(CondS02 cond) {
            this.GetTyouhyouDataGAsync(cond, null);
        }
        
        /// <remarks/>
        public void GetTyouhyouDataGAsync(CondS02 cond, object userState) {
            if ((this.GetTyouhyouDataGOperationCompleted == null)) {
                this.GetTyouhyouDataGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTyouhyouDataGOperationCompleted);
            }
            this.InvokeAsync("GetTyouhyouDataG", new object[] {
                        cond}, this.GetTyouhyouDataGOperationCompleted, userState);
        }
        
        private void OnGetTyouhyouDataGOperationCompleted(object arg) {
            if ((this.GetTyouhyouDataGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTyouhyouDataGCompleted(this, new GetTyouhyouDataGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetTyouhyouDataH", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetTyouhyouDataH(CondS02 cond) {
            object[] results = this.Invoke("GetTyouhyouDataH", new object[] {
                        cond});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetTyouhyouDataHAsync(CondS02 cond) {
            this.GetTyouhyouDataHAsync(cond, null);
        }
        
        /// <remarks/>
        public void GetTyouhyouDataHAsync(CondS02 cond, object userState) {
            if ((this.GetTyouhyouDataHOperationCompleted == null)) {
                this.GetTyouhyouDataHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTyouhyouDataHOperationCompleted);
            }
            this.InvokeAsync("GetTyouhyouDataH", new object[] {
                        cond}, this.GetTyouhyouDataHOperationCompleted, userState);
        }
        
        private void OnGetTyouhyouDataHOperationCompleted(object arg) {
            if ((this.GetTyouhyouDataHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTyouhyouDataHCompleted(this, new GetTyouhyouDataHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/SendCondBase", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendCondBase(CondBase cond) {
            this.Invoke("SendCondBase", new object[] {
                        cond});
        }
        
        /// <remarks/>
        public void SendCondBaseAsync(CondBase cond) {
            this.SendCondBaseAsync(cond, null);
        }
        
        /// <remarks/>
        public void SendCondBaseAsync(CondBase cond, object userState) {
            if ((this.SendCondBaseOperationCompleted == null)) {
                this.SendCondBaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendCondBaseOperationCompleted);
            }
            this.InvokeAsync("SendCondBase", new object[] {
                        cond}, this.SendCondBaseOperationCompleted, userState);
        }
        
        private void OnSendCondBaseOperationCompleted(object arg) {
            if ((this.SendCondBaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendCondBaseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9149")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smssrv/")]
    public partial class CondS02 : CondBase {
        
        private string shukkaNoField;
        
        private string shukkaFlagField;
        
        private string nonyusakiCDField;
        
        private string[] nonyusakiCDsField;
        
        private string aRNoField;
        
        private string kanriFlagField;
        
        private string sagyoFlagField;
        
        private string jyotaiFlagField;
        
        private object shukkaDateField;
        
        private object shukkaUserIDField;
        
        private object shukkaUserNameField;
        
        private object unsokaishaNameField;
        
        private object invoiceNoField;
        
        private object okurijyoNoField;
        
        private object bLNoField;
        
        private string boxNoField;
        
        private string nonyusakiNameField;
        
        private string shipField;
        
        private string dispSelectField;
        
        private string hinmeiJpField;
        
        private string hinmeiField;
        
        private string zumenKeishikiField;
        
        private string kiwakuNoField;
        
        private string caseNoField;
        
        private string palletNoField;
        
        private string tagNoField;
        
        private bool isKonpo2ShukkaField;
        
        private bool isShukka2ShukkaField;
        
        private string textKonpozumiField;
        
        private string textShukkaField;
        
        private string textShosaiField;
        
        private string kokunaigaiField;
        
        private string syukkaDateField;
        
        private string hakkouFlagField;
        
        private string packingNoField;
        
        private string tehaiRenkeiNoField;
        
        private string estimateNoField;
        
        private string kojiNoField;
        
        private string consignCdField;
        
        private string deliverCdField;
        
        private string unsokaishaNoField;
        
        private string internalPoNoField;
        
        private string tagShipField;
        
        /// <remarks/>
        public string ShukkaNo {
            get {
                return this.shukkaNoField;
            }
            set {
                this.shukkaNoField = value;
            }
        }
        
        /// <remarks/>
        public string ShukkaFlag {
            get {
                return this.shukkaFlagField;
            }
            set {
                this.shukkaFlagField = value;
            }
        }
        
        /// <remarks/>
        public string NonyusakiCD {
            get {
                return this.nonyusakiCDField;
            }
            set {
                this.nonyusakiCDField = value;
            }
        }
        
        /// <remarks/>
        public string[] NonyusakiCDs {
            get {
                return this.nonyusakiCDsField;
            }
            set {
                this.nonyusakiCDsField = value;
            }
        }
        
        /// <remarks/>
        public string ARNo {
            get {
                return this.aRNoField;
            }
            set {
                this.aRNoField = value;
            }
        }
        
        /// <remarks/>
        public string KanriFlag {
            get {
                return this.kanriFlagField;
            }
            set {
                this.kanriFlagField = value;
            }
        }
        
        /// <remarks/>
        public string SagyoFlag {
            get {
                return this.sagyoFlagField;
            }
            set {
                this.sagyoFlagField = value;
            }
        }
        
        /// <remarks/>
        public string JyotaiFlag {
            get {
                return this.jyotaiFlagField;
            }
            set {
                this.jyotaiFlagField = value;
            }
        }
        
        /// <remarks/>
        public object ShukkaDate {
            get {
                return this.shukkaDateField;
            }
            set {
                this.shukkaDateField = value;
            }
        }
        
        /// <remarks/>
        public object ShukkaUserID {
            get {
                return this.shukkaUserIDField;
            }
            set {
                this.shukkaUserIDField = value;
            }
        }
        
        /// <remarks/>
        public object ShukkaUserName {
            get {
                return this.shukkaUserNameField;
            }
            set {
                this.shukkaUserNameField = value;
            }
        }
        
        /// <remarks/>
        public object UnsokaishaName {
            get {
                return this.unsokaishaNameField;
            }
            set {
                this.unsokaishaNameField = value;
            }
        }
        
        /// <remarks/>
        public object InvoiceNo {
            get {
                return this.invoiceNoField;
            }
            set {
                this.invoiceNoField = value;
            }
        }
        
        /// <remarks/>
        public object OkurijyoNo {
            get {
                return this.okurijyoNoField;
            }
            set {
                this.okurijyoNoField = value;
            }
        }
        
        /// <remarks/>
        public object BLNo {
            get {
                return this.bLNoField;
            }
            set {
                this.bLNoField = value;
            }
        }
        
        /// <remarks/>
        public string BoxNo {
            get {
                return this.boxNoField;
            }
            set {
                this.boxNoField = value;
            }
        }
        
        /// <remarks/>
        public string NonyusakiName {
            get {
                return this.nonyusakiNameField;
            }
            set {
                this.nonyusakiNameField = value;
            }
        }
        
        /// <remarks/>
        public string Ship {
            get {
                return this.shipField;
            }
            set {
                this.shipField = value;
            }
        }
        
        /// <remarks/>
        public string DispSelect {
            get {
                return this.dispSelectField;
            }
            set {
                this.dispSelectField = value;
            }
        }
        
        /// <remarks/>
        public string HinmeiJp {
            get {
                return this.hinmeiJpField;
            }
            set {
                this.hinmeiJpField = value;
            }
        }
        
        /// <remarks/>
        public string Hinmei {
            get {
                return this.hinmeiField;
            }
            set {
                this.hinmeiField = value;
            }
        }
        
        /// <remarks/>
        public string ZumenKeishiki {
            get {
                return this.zumenKeishikiField;
            }
            set {
                this.zumenKeishikiField = value;
            }
        }
        
        /// <remarks/>
        public string KiwakuNo {
            get {
                return this.kiwakuNoField;
            }
            set {
                this.kiwakuNoField = value;
            }
        }
        
        /// <remarks/>
        public string CaseNo {
            get {
                return this.caseNoField;
            }
            set {
                this.caseNoField = value;
            }
        }
        
        /// <remarks/>
        public string PalletNo {
            get {
                return this.palletNoField;
            }
            set {
                this.palletNoField = value;
            }
        }
        
        /// <remarks/>
        public string TagNo {
            get {
                return this.tagNoField;
            }
            set {
                this.tagNoField = value;
            }
        }
        
        /// <remarks/>
        public bool IsKonpo2Shukka {
            get {
                return this.isKonpo2ShukkaField;
            }
            set {
                this.isKonpo2ShukkaField = value;
            }
        }
        
        /// <remarks/>
        public bool IsShukka2Shukka {
            get {
                return this.isShukka2ShukkaField;
            }
            set {
                this.isShukka2ShukkaField = value;
            }
        }
        
        /// <remarks/>
        public string TextKonpozumi {
            get {
                return this.textKonpozumiField;
            }
            set {
                this.textKonpozumiField = value;
            }
        }
        
        /// <remarks/>
        public string TextShukka {
            get {
                return this.textShukkaField;
            }
            set {
                this.textShukkaField = value;
            }
        }
        
        /// <remarks/>
        public string TextShosai {
            get {
                return this.textShosaiField;
            }
            set {
                this.textShosaiField = value;
            }
        }
        
        /// <remarks/>
        public string Kokunaigai {
            get {
                return this.kokunaigaiField;
            }
            set {
                this.kokunaigaiField = value;
            }
        }
        
        /// <remarks/>
        public string SyukkaDate {
            get {
                return this.syukkaDateField;
            }
            set {
                this.syukkaDateField = value;
            }
        }
        
        /// <remarks/>
        public string HakkouFlag {
            get {
                return this.hakkouFlagField;
            }
            set {
                this.hakkouFlagField = value;
            }
        }
        
        /// <remarks/>
        public string PackingNo {
            get {
                return this.packingNoField;
            }
            set {
                this.packingNoField = value;
            }
        }
        
        /// <remarks/>
        public string TehaiRenkeiNo {
            get {
                return this.tehaiRenkeiNoField;
            }
            set {
                this.tehaiRenkeiNoField = value;
            }
        }
        
        /// <remarks/>
        public string EstimateNo {
            get {
                return this.estimateNoField;
            }
            set {
                this.estimateNoField = value;
            }
        }
        
        /// <remarks/>
        public string KojiNo {
            get {
                return this.kojiNoField;
            }
            set {
                this.kojiNoField = value;
            }
        }
        
        /// <remarks/>
        public string ConsignCd {
            get {
                return this.consignCdField;
            }
            set {
                this.consignCdField = value;
            }
        }
        
        /// <remarks/>
        public string DeliverCd {
            get {
                return this.deliverCdField;
            }
            set {
                this.deliverCdField = value;
            }
        }
        
        /// <remarks/>
        public string UnsokaishaNo {
            get {
                return this.unsokaishaNoField;
            }
            set {
                this.unsokaishaNoField = value;
            }
        }
        
        /// <remarks/>
        public string InternalPoNo {
            get {
                return this.internalPoNoField;
            }
            set {
                this.internalPoNoField = value;
            }
        }
        
        /// <remarks/>
        public string TagShip {
            get {
                return this.tagShipField;
            }
            set {
                this.tagShipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9149")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smssrv/")]
    public partial class LoginInfo {
        
        private string userIDField;
        
        private string userNameField;
        
        private string pcNameField;
        
        private string[] iPAddressField;
        
        private string roleIDField;
        
        private string roleNameField;
        
        private string languageField;
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string PcName {
            get {
                return this.pcNameField;
            }
            set {
                this.pcNameField = value;
            }
        }
        
        /// <remarks/>
        public string[] IPAddress {
            get {
                return this.iPAddressField;
            }
            set {
                this.iPAddressField = value;
            }
        }
        
        /// <remarks/>
        public string RoleID {
            get {
                return this.roleIDField;
            }
            set {
                this.roleIDField = value;
            }
        }
        
        /// <remarks/>
        public string RoleName {
            get {
                return this.roleNameField;
            }
            set {
                this.roleNameField = value;
            }
        }
        
        /// <remarks/>
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CondS02))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9149")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smssrv/")]
    public partial class CondBase {
        
        private LoginInfo loginInfoField;
        
        private object createDateField;
        
        private string createUserIDField;
        
        private string createUserNameField;
        
        private object updateDateField;
        
        private string updateUserIDField;
        
        private string updateUserNameField;
        
        private object mainteDateField;
        
        private string mainteUserIDField;
        
        private string mainteUserNameField;
        
        private string versionField;
        
        /// <remarks/>
        public LoginInfo LoginInfo {
            get {
                return this.loginInfoField;
            }
            set {
                this.loginInfoField = value;
            }
        }
        
        /// <remarks/>
        public object CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        public string CreateUserID {
            get {
                return this.createUserIDField;
            }
            set {
                this.createUserIDField = value;
            }
        }
        
        /// <remarks/>
        public string CreateUserName {
            get {
                return this.createUserNameField;
            }
            set {
                this.createUserNameField = value;
            }
        }
        
        /// <remarks/>
        public object UpdateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
            }
        }
        
        /// <remarks/>
        public string UpdateUserID {
            get {
                return this.updateUserIDField;
            }
            set {
                this.updateUserIDField = value;
            }
        }
        
        /// <remarks/>
        public string UpdateUserName {
            get {
                return this.updateUserNameField;
            }
            set {
                this.updateUserNameField = value;
            }
        }
        
        /// <remarks/>
        public object MainteDate {
            get {
                return this.mainteDateField;
            }
            set {
                this.mainteDateField = value;
            }
        }
        
        /// <remarks/>
        public string MainteUserID {
            get {
                return this.mainteUserIDField;
            }
            set {
                this.mainteUserIDField = value;
            }
        }
        
        /// <remarks/>
        public string MainteUserName {
            get {
                return this.mainteUserNameField;
            }
            set {
                this.mainteUserNameField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetBoxDataCompletedEventHandler(object sender, GetBoxDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBoxDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBoxDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errMsgID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] args {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetPalletDataCompletedEventHandler(object sender, GetPalletDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPalletDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPalletDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errMsgID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] args {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetKiwakuDataCompletedEventHandler(object sender, GetKiwakuDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetKiwakuDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetKiwakuDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errMsgID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] args {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void UpdBoxDataCompletedEventHandler(object sender, UpdBoxDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdBoxDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdBoxDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errMsgID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] args {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void UpdPalletDataCompletedEventHandler(object sender, UpdPalletDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdPalletDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdPalletDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errMsgID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] args {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void UpdKiwakuDataCompletedEventHandler(object sender, UpdKiwakuDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdKiwakuDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdKiwakuDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errMsgID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] args {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetBoxMeisaiCompletedEventHandler(object sender, GetBoxMeisaiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBoxMeisaiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBoxMeisaiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetShukkaMeisaiCompletedEventHandler(object sender, GetShukkaMeisaiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetShukkaMeisaiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetShukkaMeisaiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errMsgID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] args {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetConsignCompletedEventHandler(object sender, GetConsignCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetConsignCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetConsignCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetDeliverCompletedEventHandler(object sender, GetDeliverCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDeliverCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDeliverCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetNisugataCompletedEventHandler(object sender, GetNisugataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNisugataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNisugataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void CheckInvoiceCompletedEventHandler(object sender, CheckInvoiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckInvoiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckInvoiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void UpdShippingDataCompletedEventHandler(object sender, UpdShippingDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdShippingDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdShippingDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string errMsgID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string[] args {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetShippingDocumentCompletedEventHandler(object sender, GetShippingDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetShippingDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetShippingDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetTyouhyouDataDCompletedEventHandler(object sender, GetTyouhyouDataDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTyouhyouDataDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTyouhyouDataDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetTyouhyouDataECompletedEventHandler(object sender, GetTyouhyouDataECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTyouhyouDataECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTyouhyouDataECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetTyouhyouDataGCompletedEventHandler(object sender, GetTyouhyouDataGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTyouhyouDataGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTyouhyouDataGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetTyouhyouDataHCompletedEventHandler(object sender, GetTyouhyouDataHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTyouhyouDataHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTyouhyouDataHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void SendCondBaseCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591