//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.9174
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// このソース コードは Microsoft.VSDesigner、バージョン 2.0.50727.9174 によって自動生成されました。
// 
#pragma warning disable 1591

namespace WsConnection.WebRefMaster {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsMasterSoap", Namespace="http://smssrv/")]
    public partial class WsMaster : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetNonyusakiOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRoleOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendCondBaseOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsMaster() {
            this.Url = global::WsConnection.Properties.Settings.Default.WsConnection_WebRefMaster_WsMaster;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetNonyusakiCompletedEventHandler GetNonyusakiCompleted;
        
        /// <remarks/>
        public event GetRoleCompletedEventHandler GetRoleCompleted;
        
        /// <remarks/>
        public event SendCondBaseCompletedEventHandler SendCondBaseCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetNonyusaki", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetNonyusaki(CondNonyusaki cond) {
            object[] results = this.Invoke("GetNonyusaki", new object[] {
                        cond});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetNonyusakiAsync(CondNonyusaki cond) {
            this.GetNonyusakiAsync(cond, null);
        }
        
        /// <remarks/>
        public void GetNonyusakiAsync(CondNonyusaki cond, object userState) {
            if ((this.GetNonyusakiOperationCompleted == null)) {
                this.GetNonyusakiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNonyusakiOperationCompleted);
            }
            this.InvokeAsync("GetNonyusaki", new object[] {
                        cond}, this.GetNonyusakiOperationCompleted, userState);
        }
        
        private void OnGetNonyusakiOperationCompleted(object arg) {
            if ((this.GetNonyusakiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNonyusakiCompleted(this, new GetNonyusakiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/GetRole", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetRole(CondRole cond) {
            object[] results = this.Invoke("GetRole", new object[] {
                        cond});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetRoleAsync(CondRole cond) {
            this.GetRoleAsync(cond, null);
        }
        
        /// <remarks/>
        public void GetRoleAsync(CondRole cond, object userState) {
            if ((this.GetRoleOperationCompleted == null)) {
                this.GetRoleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRoleOperationCompleted);
            }
            this.InvokeAsync("GetRole", new object[] {
                        cond}, this.GetRoleOperationCompleted, userState);
        }
        
        private void OnGetRoleOperationCompleted(object arg) {
            if ((this.GetRoleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRoleCompleted(this, new GetRoleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://smssrv/SendCondBase", RequestNamespace="http://smssrv/", ResponseNamespace="http://smssrv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendCondBase(CondBase cond) {
            this.Invoke("SendCondBase", new object[] {
                        cond});
        }
        
        /// <remarks/>
        public void SendCondBaseAsync(CondBase cond) {
            this.SendCondBaseAsync(cond, null);
        }
        
        /// <remarks/>
        public void SendCondBaseAsync(CondBase cond, object userState) {
            if ((this.SendCondBaseOperationCompleted == null)) {
                this.SendCondBaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendCondBaseOperationCompleted);
            }
            this.InvokeAsync("SendCondBase", new object[] {
                        cond}, this.SendCondBaseOperationCompleted, userState);
        }
        
        private void OnSendCondBaseOperationCompleted(object arg) {
            if ((this.SendCondBaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendCondBaseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9149")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smssrv/")]
    public partial class CondNonyusaki : CondBase {
        
        private string shukkaFlagField;
        
        private string nonyusakiCDField;
        
        private string nonyusakiNameField;
        
        private string shipField;
        
        private string kanriFlagField;
        
        private string listFlagName0Field;
        
        private string listFlagName1Field;
        
        private string listFlagName2Field;
        
        private string listFlagName3Field;
        
        private string listFlagName4Field;
        
        private string listFlagName5Field;
        
        private string listFlagName6Field;
        
        private string listFlagName7Field;
        
        private string removeFlagField;
        
        private string bukkenNoField;
        
        private string gamenFlagField;
        
        private string transportFlagField;
        
        private string estimateFlagField;
        
        private string shipDateField;
        
        private string shipFromField;
        
        private string shipToField;
        
        private string shipNoField;
        
        private string shipSeibanField;
        
        private string shipFromCDField;
        
        private string tagShipField;
        
        private string syoriFlagField;
        
        private string seibanField;
        
        private string kishuField;
        
        private string naiyoField;
        
        private string touchakuyoteiDateField;
        
        private string kikaiPartsField;
        
        private string seigyoPartsField;
        
        private string bikoField;
        
        private string consignNameField;
        
        /// <remarks/>
        public string ShukkaFlag {
            get {
                return this.shukkaFlagField;
            }
            set {
                this.shukkaFlagField = value;
            }
        }
        
        /// <remarks/>
        public string NonyusakiCD {
            get {
                return this.nonyusakiCDField;
            }
            set {
                this.nonyusakiCDField = value;
            }
        }
        
        /// <remarks/>
        public string NonyusakiName {
            get {
                return this.nonyusakiNameField;
            }
            set {
                this.nonyusakiNameField = value;
            }
        }
        
        /// <remarks/>
        public string Ship {
            get {
                return this.shipField;
            }
            set {
                this.shipField = value;
            }
        }
        
        /// <remarks/>
        public string KanriFlag {
            get {
                return this.kanriFlagField;
            }
            set {
                this.kanriFlagField = value;
            }
        }
        
        /// <remarks/>
        public string ListFlagName0 {
            get {
                return this.listFlagName0Field;
            }
            set {
                this.listFlagName0Field = value;
            }
        }
        
        /// <remarks/>
        public string ListFlagName1 {
            get {
                return this.listFlagName1Field;
            }
            set {
                this.listFlagName1Field = value;
            }
        }
        
        /// <remarks/>
        public string ListFlagName2 {
            get {
                return this.listFlagName2Field;
            }
            set {
                this.listFlagName2Field = value;
            }
        }
        
        /// <remarks/>
        public string ListFlagName3 {
            get {
                return this.listFlagName3Field;
            }
            set {
                this.listFlagName3Field = value;
            }
        }
        
        /// <remarks/>
        public string ListFlagName4 {
            get {
                return this.listFlagName4Field;
            }
            set {
                this.listFlagName4Field = value;
            }
        }
        
        /// <remarks/>
        public string ListFlagName5 {
            get {
                return this.listFlagName5Field;
            }
            set {
                this.listFlagName5Field = value;
            }
        }
        
        /// <remarks/>
        public string ListFlagName6 {
            get {
                return this.listFlagName6Field;
            }
            set {
                this.listFlagName6Field = value;
            }
        }
        
        /// <remarks/>
        public string ListFlagName7 {
            get {
                return this.listFlagName7Field;
            }
            set {
                this.listFlagName7Field = value;
            }
        }
        
        /// <remarks/>
        public string RemoveFlag {
            get {
                return this.removeFlagField;
            }
            set {
                this.removeFlagField = value;
            }
        }
        
        /// <remarks/>
        public string BukkenNo {
            get {
                return this.bukkenNoField;
            }
            set {
                this.bukkenNoField = value;
            }
        }
        
        /// <remarks/>
        public string GamenFlag {
            get {
                return this.gamenFlagField;
            }
            set {
                this.gamenFlagField = value;
            }
        }
        
        /// <remarks/>
        public string TransportFlag {
            get {
                return this.transportFlagField;
            }
            set {
                this.transportFlagField = value;
            }
        }
        
        /// <remarks/>
        public string EstimateFlag {
            get {
                return this.estimateFlagField;
            }
            set {
                this.estimateFlagField = value;
            }
        }
        
        /// <remarks/>
        public string ShipDate {
            get {
                return this.shipDateField;
            }
            set {
                this.shipDateField = value;
            }
        }
        
        /// <remarks/>
        public string ShipFrom {
            get {
                return this.shipFromField;
            }
            set {
                this.shipFromField = value;
            }
        }
        
        /// <remarks/>
        public string ShipTo {
            get {
                return this.shipToField;
            }
            set {
                this.shipToField = value;
            }
        }
        
        /// <remarks/>
        public string ShipNo {
            get {
                return this.shipNoField;
            }
            set {
                this.shipNoField = value;
            }
        }
        
        /// <remarks/>
        public string ShipSeiban {
            get {
                return this.shipSeibanField;
            }
            set {
                this.shipSeibanField = value;
            }
        }
        
        /// <remarks/>
        public string ShipFromCD {
            get {
                return this.shipFromCDField;
            }
            set {
                this.shipFromCDField = value;
            }
        }
        
        /// <remarks/>
        public string TagShip {
            get {
                return this.tagShipField;
            }
            set {
                this.tagShipField = value;
            }
        }
        
        /// <remarks/>
        public string SyoriFlag {
            get {
                return this.syoriFlagField;
            }
            set {
                this.syoriFlagField = value;
            }
        }
        
        /// <remarks/>
        public string Seiban {
            get {
                return this.seibanField;
            }
            set {
                this.seibanField = value;
            }
        }
        
        /// <remarks/>
        public string Kishu {
            get {
                return this.kishuField;
            }
            set {
                this.kishuField = value;
            }
        }
        
        /// <remarks/>
        public string Naiyo {
            get {
                return this.naiyoField;
            }
            set {
                this.naiyoField = value;
            }
        }
        
        /// <remarks/>
        public string TouchakuyoteiDate {
            get {
                return this.touchakuyoteiDateField;
            }
            set {
                this.touchakuyoteiDateField = value;
            }
        }
        
        /// <remarks/>
        public string KikaiParts {
            get {
                return this.kikaiPartsField;
            }
            set {
                this.kikaiPartsField = value;
            }
        }
        
        /// <remarks/>
        public string SeigyoParts {
            get {
                return this.seigyoPartsField;
            }
            set {
                this.seigyoPartsField = value;
            }
        }
        
        /// <remarks/>
        public string Biko {
            get {
                return this.bikoField;
            }
            set {
                this.bikoField = value;
            }
        }
        
        /// <remarks/>
        public string ConsignName {
            get {
                return this.consignNameField;
            }
            set {
                this.consignNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CondRole))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CondNonyusaki))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9149")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smssrv/")]
    public partial class CondBase {
        
        private LoginInfo loginInfoField;
        
        private object createDateField;
        
        private string createUserIDField;
        
        private string createUserNameField;
        
        private object updateDateField;
        
        private string updateUserIDField;
        
        private string updateUserNameField;
        
        private object mainteDateField;
        
        private string mainteUserIDField;
        
        private string mainteUserNameField;
        
        private string versionField;
        
        /// <remarks/>
        public LoginInfo LoginInfo {
            get {
                return this.loginInfoField;
            }
            set {
                this.loginInfoField = value;
            }
        }
        
        /// <remarks/>
        public object CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        public string CreateUserID {
            get {
                return this.createUserIDField;
            }
            set {
                this.createUserIDField = value;
            }
        }
        
        /// <remarks/>
        public string CreateUserName {
            get {
                return this.createUserNameField;
            }
            set {
                this.createUserNameField = value;
            }
        }
        
        /// <remarks/>
        public object UpdateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
            }
        }
        
        /// <remarks/>
        public string UpdateUserID {
            get {
                return this.updateUserIDField;
            }
            set {
                this.updateUserIDField = value;
            }
        }
        
        /// <remarks/>
        public string UpdateUserName {
            get {
                return this.updateUserNameField;
            }
            set {
                this.updateUserNameField = value;
            }
        }
        
        /// <remarks/>
        public object MainteDate {
            get {
                return this.mainteDateField;
            }
            set {
                this.mainteDateField = value;
            }
        }
        
        /// <remarks/>
        public string MainteUserID {
            get {
                return this.mainteUserIDField;
            }
            set {
                this.mainteUserIDField = value;
            }
        }
        
        /// <remarks/>
        public string MainteUserName {
            get {
                return this.mainteUserNameField;
            }
            set {
                this.mainteUserNameField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9149")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smssrv/")]
    public partial class LoginInfo {
        
        private string userIDField;
        
        private string userNameField;
        
        private string pcNameField;
        
        private string[] iPAddressField;
        
        private string roleIDField;
        
        private string roleNameField;
        
        private string languageField;
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string PcName {
            get {
                return this.pcNameField;
            }
            set {
                this.pcNameField = value;
            }
        }
        
        /// <remarks/>
        public string[] IPAddress {
            get {
                return this.iPAddressField;
            }
            set {
                this.iPAddressField = value;
            }
        }
        
        /// <remarks/>
        public string RoleID {
            get {
                return this.roleIDField;
            }
            set {
                this.roleIDField = value;
            }
        }
        
        /// <remarks/>
        public string RoleName {
            get {
                return this.roleNameField;
            }
            set {
                this.roleNameField = value;
            }
        }
        
        /// <remarks/>
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.9149")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://smssrv/")]
    public partial class CondRole : CondBase {
        
        private string roleIDField;
        
        private string roleNameField;
        
        private string roleFlagField;
        
        /// <remarks/>
        public string RoleID {
            get {
                return this.roleIDField;
            }
            set {
                this.roleIDField = value;
            }
        }
        
        /// <remarks/>
        public string RoleName {
            get {
                return this.roleNameField;
            }
            set {
                this.roleNameField = value;
            }
        }
        
        /// <remarks/>
        public string RoleFlag {
            get {
                return this.roleFlagField;
            }
            set {
                this.roleFlagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetNonyusakiCompletedEventHandler(object sender, GetNonyusakiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNonyusakiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNonyusakiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void GetRoleCompletedEventHandler(object sender, GetRoleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRoleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRoleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.9149")]
    public delegate void SendCondBaseCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591